package org.tio.sitexxx.service.model.stat;

import org.tio.sitexxx.service.model.stat.base.BaseStatUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class StatUser extends BaseStatUser<StatUser> {
	public static final StatUser dao = new StatUser().dao();
}
