/*
 * 使用本软件请从杭州钛特云有限公司获取授权，其它途径获取本软件的行为皆为侵权行为
 * 本源代码由杭州钛特云科技有限公司授权给娄底大新土石方施工有限公司使用
 */
package org.tio.sitexxx.service.model.stat;

import org.tio.sitexxx.service.model.stat.base.BaseTioIpPullblackLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TioIpPullblackLog extends BaseTioIpPullblackLog<TioIpPullblackLog> {
	public static final TioIpPullblackLog dao = new TioIpPullblackLog().dao();

	public static interface Type {
		/**
		 * http请求太频繁
		 */
		byte HTTP_REQUEST_TOO_FREQUENTLY = (byte) 1;

		/**
		 * 恶意攻击，后面分类再定 
		 */
		byte ATTACK = (byte) 2;

		/**
		 * 被人工拉黑
		 */
		byte MANUAL = (byte) 3;

		/**
		 * IM请求太频繁
		 */
		byte IM_REQUEST_TOO_FREQUENTLY = (byte) 4;
	}
}
