package org.tio.sitexxx.service.model.main;

import org.tio.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("audio", "id", Audio.class);
		arp.addMapping("chatroom_join_leave", "id", ChatroomJoinLeave.class);
		arp.addMapping("email_send_log", "id", EmailSendLog.class);
		arp.addMapping("file", "id", File.class);
		arp.addMapping("img", "id", Img.class);
		arp.addMapping("ip_info", "id", IpInfo.class);
		arp.addMapping("login_log", "id", LoginLog.class);
		arp.addMapping("login_task_items", "id", LoginTaskItems.class);
		arp.addMapping("oauth2_client", "id", Oauth2Client.class);
		arp.addMapping("recharge_item", "id", RechargeItem.class);
		arp.addMapping("role", "id", Role.class);
		arp.addMapping("sms_log", "id", SmsLog.class);
		arp.addMapping("stat_online", "id", StatOnline.class);
		arp.addMapping("tio_thread_logs", "id", TioThreadLogs.class);
		arp.addMapping("user", "id", User.class);
		arp.addMapping("user_action_log", "id", UserActionLog.class);
		arp.addMapping("user_address", "id", UserAddress.class);
		arp.addMapping("user_agent", "id", UserAgent.class);
		arp.addMapping("user_base", "id", UserBase.class);
		arp.addMapping("user_coin", "id", UserCoin.class);
		arp.addMapping("user_coin_item", "id", UserCoinItem.class);
		arp.addMapping("user_ext", "id", UserExt.class);
		arp.addMapping("user_info_syn", "id", UserInfoSyn.class);
		arp.addMapping("user_invite", "id", UserInvite.class);
		arp.addMapping("user_invite_attr", "id", UserInviteAttr.class);
		arp.addMapping("user_last_login_time", "id", UserLastLoginTime.class);
		arp.addMapping("user_msg", "id", UserMsg.class);
		arp.addMapping("user_role", "id", UserRole.class);
		arp.addMapping("user_third", "id", UserThird.class);
		arp.addMapping("user_third_osc", "id", UserThirdOsc.class);
		arp.addMapping("user_third_qq", "id", UserThirdQq.class);
		arp.addMapping("user_third_weibo", "id", UserThirdWeibo.class);
		arp.addMapping("user_third_wx", "id", UserThirdWx.class);
		// Composite Primary Key order: devicetype,uid
		arp.addMapping("user_token", "devicetype,uid", UserToken.class);
		arp.addMapping("user_vip_level", "id", UserVipLevel.class);
		arp.addMapping("userlog_modify_avatar", "id", UserlogModifyAvatar.class);
		arp.addMapping("userlog_modify_nick", "id", UserlogModifyNick.class);
		arp.addMapping("video", "id", Video.class);
		arp.addMapping("video_oper_log", "id", VideoOperLog.class);
		arp.addMapping("wx_app", "id", WxApp.class);
		arp.addMapping("wx_call_item", "id", WxCallItem.class);
		arp.addMapping("wx_call_log", "id", WxCallLog.class);
		arp.addMapping("wx_chat_del_item", "id", WxChatDelItem.class);
		// Composite Primary Key order: groupid,uid
		arp.addMapping("wx_chat_group_item", "groupid,uid", WxChatGroupItem.class);
		arp.addMapping("wx_chat_items", "id", WxChatItems.class);
		arp.addMapping("wx_chat_items_meta", "id", WxChatItemsMeta.class);
		// Composite Primary Key order: uid,chatmode,bizid
		arp.addMapping("wx_chat_user_item", "uid,chatmode,bizid", WxChatUserItem.class);
		arp.addMapping("wx_friend", "id", WxFriend.class);
		arp.addMapping("wx_friend_apply_items", "id", WxFriendApplyItems.class);
		arp.addMapping("wx_friend_apply_log", "id", WxFriendApplyLog.class);
		arp.addMapping("wx_friend_del_log", "id", WxFriendDelLog.class);
		arp.addMapping("wx_friend_group", "id", WxFriendGroup.class);
		arp.addMapping("wx_friend_meta", "id", WxFriendMeta.class);
		arp.addMapping("wx_friend_msg", "id", WxFriendMsg.class);
		arp.addMapping("wx_friend_oper_msg", "id", WxFriendOperMsg.class);
		arp.addMapping("wx_group", "id", WxGroup.class);
		arp.addMapping("wx_group_apply", "id", WxGroupApply.class);
		arp.addMapping("wx_group_apply_items", "id", WxGroupApplyItems.class);
		arp.addMapping("wx_group_meta", "id", WxGroupMeta.class);
		arp.addMapping("wx_group_msg", "id", WxGroupMsg.class);
		arp.addMapping("wx_group_msg_user_oper", "id", WxGroupMsgUserOper.class);
		arp.addMapping("wx_group_user", "id", WxGroupUser.class);
		arp.addMapping("wx_group_user_del_log", "id", WxGroupUserDelLog.class);
		arp.addMapping("wx_group_user_invite_log", "id", WxGroupUserInviteLog.class);
		arp.addMapping("wx_jpush_user", "id", WxJpushUser.class);
		arp.addMapping("wx_read_ack", "id", WxReadAck.class);
		arp.addMapping("wx_syn_item", "id", WxSynItem.class);
		arp.addMapping("wx_syn_item_bak", "id", WxSynItemBak.class);
		arp.addMapping("wx_tag", "id", WxTag.class);
		arp.addMapping("wx_tag_friend", "id", WxTagFriend.class);
		arp.addMapping("wx_task_items", "id", WxTaskItems.class);
		arp.addMapping("wx_user_bank_card", "id", WxUserBankCard.class);
		arp.addMapping("wx_user_black_items", "id", WxUserBlackItems.class);
		arp.addMapping("wx_user_coin", "id", WxUserCoin.class);
		arp.addMapping("wx_user_coin_item", "id", WxUserCoinItem.class);
		arp.addMapping("wx_user_grab_red_item", "id", WxUserGrabRedItem.class);
		arp.addMapping("wx_user_realname", "id", WxUserRealname.class);
		arp.addMapping("wx_user_recharge_item", "id", WxUserRechargeItem.class);
		arp.addMapping("wx_user_red_packet", "id", WxUserRedPacket.class);
		arp.addMapping("wx_user_red_packet_item", "id", WxUserRedPacketItem.class);
		arp.addMapping("wx_user_send_red_item", "id", WxUserSendRedItem.class);
		arp.addMapping("wx_user_wallet", "id", WxUserWallet.class);
		arp.addMapping("wx_user_withhold_count", "id", WxUserWithholdCount.class);
		arp.addMapping("wx_user_withhold_item", "id", WxUserWithholdItem.class);
		arp.addMapping("yx_admin_reciever_account", "id", YxAdminRecieverAccount.class);
		arp.addMapping("yx_collect", "id", YxCollect.class);
		arp.addMapping("yx_onekey_login_tmp", "id", YxOnekeyLoginTmp.class);
		arp.addMapping("yx_trans_accounts", "id", YxTransAccounts.class);
		arp.addMapping("yx_user_recharge", "id", YxUserRecharge.class);
		arp.addMapping("yx_user_reciever_red_packet_item", "id", YxUserRecieverRedPacketItem.class);
		arp.addMapping("yx_user_send_red_packet", "id", YxUserSendRedPacket.class);
		arp.addMapping("yx_user_wallet", "id", YxUserWallet.class);
		arp.addMapping("yx_user_wallet_item", "id", YxUserWalletItem.class);
		arp.addMapping("yx_user_withdraw", "id", YxUserWithdraw.class);
		arp.addMapping("yx_user_withdraw_account", "id", YxUserWithdrawAccount.class);
	}
}

