/*
 * 使用本软件请从杭州钛特云有限公司获取授权，其它途径获取本软件的行为皆为侵权行为
 * 本源代码由杭州钛特云科技有限公司授权给娄底大新土石方施工有限公司使用
 */
package org.tio.sitexxx.service.model.main;

import org.tio.sitexxx.service.model.main.base.BaseChatroomJoinLeave;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ChatroomJoinLeave extends BaseChatroomJoinLeave<ChatroomJoinLeave> {
	public static final ChatroomJoinLeave dao = new ChatroomJoinLeave().dao();
	
	private boolean isChat = false;

	/**
	 * @return the isChat
	 */
	public boolean isChat() {
		return isChat;
	}

	/**
	 * @param isChat the isChat to set
	 */
	public void setChat(boolean isChat) {
		this.isChat = isChat;
	}
}
