/*
 * 使用本软件请从杭州钛特云有限公司获取授权，其它途径获取本软件的行为皆为侵权行为
 * 本源代码由杭州钛特云科技有限公司授权给娄底大新土石方施工有限公司使用
 */
package org.tio.sitexxx.service.model.main;

import org.tio.sitexxx.service.model.main.base.BaseFile;
import org.tio.sitexxx.servicecommon.vo.Const;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class File extends BaseFile<File> {
	public static final File dao = new File().dao();
	
	private Byte fileicontype;

	public Byte getFileicontype() {
		this.fileicontype = iconType(getExt());
		return fileicontype;
	}

	public void setFileicontype(Byte fileicontype) {
		this.fileicontype = fileicontype;
	}
	
	
	
	/**
	 * @param ext
	 * @return
	 * @author xufei
	 * 2020年9月18日 下午3:41:07
	 */
	public static Byte iconType(String ext) {
		Byte icon = Const.FileIconType.OTHER;
		switch (ext.toLowerCase()) {
		case "pdf":
			icon = Const.FileIconType.PDF;
			break;
		case "txt":
			icon = Const.FileIconType.TXT;
			break;
		case "doc":
		case "docx":
			icon = Const.FileIconType.DOC;
			break;
		case "xls":
		case "xlsx":
			icon = Const.FileIconType.XLS;
			break;
		case "ppt":
		case "pptx":
			icon = Const.FileIconType.PPT;
			break;
		case "apk":
			icon = Const.FileIconType.APK;
			break;
		case "jpg":
		case "png":
		case "gif":
		case "bmp":
		case "jpeg":
			icon = Const.FileIconType.IMG;
			break;
		case "zip":
		case "rar":
		case "7z":
		case "tar":
		case "jar":
			icon = Const.FileIconType.ZIP;
			break;
		case "mp4":
		case "mov":
		case "avi":
		case "wmv":
		case "3gp":
		case "flv":
		case "mpg":
		case "mpeg":
		case "rmvb":
		case "f4v":
		case "mkv":
		case "asf":
		case "m4v":
			icon = Const.FileIconType.VIDEO;
			break;
		case "mp3":
		case "wma":
		case "aac":
		case "aiff":
		case "amr":
		case "ac3":
		case "m4a":
		case "ogg":
		case "wav":
			icon = Const.FileIconType.AUDIO;
			break;
		default:
			
		}
		return icon;
	}
	
}
