/*
 * 使用本软件请从杭州钛特云有限公司获取授权，其它途径获取本软件的行为皆为侵权行为
 * 本源代码由杭州钛特云科技有限公司授权给娄底大新土石方施工有限公司使用
 */
package org.tio.sitexxx.service.model.main;

import org.tio.sitexxx.service.model.main.base.BaseRole;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Role extends BaseRole<Role> {


	/**
	 * 超级管理员
	 */
	public static final byte ADMIN_SUPER = 99;

	/**
	 * 普通管理员
	 */
	public static final byte ADMIN_NORMAL = 1;

	/**
	 * 用户
	 */
	public static final byte NORMAL = 2;

	/**
	 * 上传视频的角色
	 */
	public static final byte UPLOAD_VIDEO = 6;

	/**
	 * 允许阅读文档的角色
	 */
	public static final byte ALLOW_READ_DOC = 7;//allow_read_doc
	
	/**
	 * 已经支付过脚手架源代码的角色
	 */
	public static final byte PAID_DOC_CODE = 8; //paid_doc
	
	/**
	 *   已经购买t-io官网源代码的角色
	 */
	public static final byte PAID_SITECODE = 9; 
	
	/**
	 *	钛信文档权限
	 */
	public static final byte DOC_TAIXIN_DOC_ROLE = 15;

	/**
	 * 购买了官网代码旗舰版的用户
	 */
	public static final byte PAID_SITECODE_QIJIAN = 94; 
	
	/**
	 *  购买了官网代码白金版的用户
	 */
	public static final byte PAID_SITECODE_BAIJIN = 95; 
	
	/**
	 * 购买了tio-chat普及版的用户
	 */
	public static final byte PAID_TIOCHAT_BASE = 96; 


}
