package org.tio.sitexxx.service.model.main;

import org.tio.sitexxx.service.model.main.base.BaseUserVipLevel;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserVipLevel extends BaseUserVipLevel<UserVipLevel> {
	public static final UserVipLevel dao = new UserVipLevel().dao();
}
