package org.tio.sitexxx.service.model.main;

import org.tio.sitexxx.service.model.main.base.BaseUserInviteAttr;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserInviteAttr extends BaseUserInviteAttr<UserInviteAttr> {
	public static final UserInviteAttr dao = new UserInviteAttr().dao();
}
