package org.tio.sitexxx.service.model.main;

import org.tio.sitexxx.service.model.main.base.BaseUserExt;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserExt extends BaseUserExt<UserExt> {
	public static final UserExt dao = new UserExt().dao();

	public UserExt() {
	}

	public UserExt(String extName, String extValue) {
		this.setExtName(extName);
		this.setExtValue(extValue);
	}
}
