/*
 * 使用本软件请从杭州钛特云有限公司获取授权，其它途径获取本软件的行为皆为侵权行为
 * 本源代码由杭州钛特云科技有限公司授权给娄底大新土石方施工有限公司使用
 */
package org.tio.sitexxx.service.model.main;

import org.tio.sitexxx.service.model.main.base.BaseWxChatUserItem;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WxChatUserItem extends BaseWxChatUserItem<WxChatUserItem> {
	public static final WxChatUserItem dao = new WxChatUserItem().dao();
	
	public static interface UserIndexOper {
		/**
		 * 	关联用户
		 */
		byte ADD_FRIEND = 1;
		
		/**
		 * 移除聊天会话
		 */
		byte REMOVE_CHAT = 2;

		
		/**
		 * 隐藏聊天-好友黑名单/删除不清消息
		 */
		byte BLOCK_CHAT = 3;
		
		/**
		 * 删除好友
		 */
		byte DEL_FRIEND = 4;
		
		/**
		 *   被删除好友
		 */
		byte TO_DEL_FRIEND =5;
		
		/**
		 * 恢复聊天-好友黑名单专用
		 */
		byte REMOVE_BLOCK_CHAT = 6;
		
		/**
		 * 激活聊天
		 */
		byte CHAT_ITEM_ACT = 7;
		
		/**
		 * 清空聊天消息
		 */
		byte CLEAR_CHAT_MSG = 8;
	}
	
}
