/*
 * 使用本软件请从杭州钛特云有限公司获取授权，其它途径获取本软件的行为皆为侵权行为
 * 本源代码由杭州钛特云科技有限公司授权给娄底大新土石方施工有限公司使用
 */
package org.tio.sitexxx.service.model.main;

import org.tio.sitexxx.service.model.main.base.BaseWxGroup;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WxGroup extends BaseWxGroup<WxGroup> {
	public static final WxGroup dao = new WxGroup().dao();
	public static final String DEFAULT_GROUP_AVATAR = "/img/group.png";
	
	public void setMetaid(java.lang.Long metaid) {
		put("metaid", metaid);
	}
	
	public java.lang.Long getMetaid() {
		return getLong("metaid");
	}
	
	/**
	 * 群人数
	 */
	public void setJoinnum(java.lang.Short joinnum) {
		put("joinnum", joinnum);
	}
	
	/**
	 * 群人数
	 */
	public java.lang.Short getJoinnum() {
		return getShort("joinnum");
	}
	
	/**
	 * 所有都激活：1：是；2：否
	 */
	public void setAllactflag(java.lang.Byte allactflag) {
		put("allactflag", allactflag);
	}
	
	/**
	 * 所有都激活：1：是；2：否
	 */
	public java.lang.Byte getAllactflag() {
		return getByte("allactflag");
	}

	/**
	 * 所有都有消息：1：是；2：否
	 */
	public void setAllstartflag(java.lang.Byte allstartflag) {
		put("allstartflag", allstartflag);
	}
	
	/**
	 * 所有都有消息：1：是；2：否
	 */
	public java.lang.Byte getAllstartflag() {
		return getByte("allstartflag");
	}
	
	/**
	 * 全员禁用：1：是；2：否
	 */
	public void setForbiddenflag(java.lang.Byte forbiddenflag) {
		put("forbiddenflag", forbiddenflag);
	}
	
	/**
	 * 全员禁用：1：是；2：否
	 */
	public java.lang.Byte getForbiddenflag() {
		return getByte("forbiddenflag");
	}
}
