/*
 * 使用本软件请从杭州钛特云有限公司获取授权，其它途径获取本软件的行为皆为侵权行为
 * 本源代码由杭州钛特云科技有限公司授权给娄底大新土石方施工有限公司使用
 */package org.tio.sitexxx.service.model.main;

import org.tio.sitexxx.service.model.main.base.BaseWxUserCoinItem;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WxUserCoinItem extends BaseWxUserCoinItem<WxUserCoinItem> {
	public static final WxUserCoinItem dao = new WxUserCoinItem().dao();
	
	public Byte oper;

	public Byte getOper() {
		return oper;
	}

	public void setOper(Byte oper) {
		this.oper = oper;
	}
	
	/**
	 * 操作码
	 * @author xufei
	 * 2020年11月26日 下午1:49:48
	 */
	public static interface CoinOper {
		/**
		 * 新增
		 */
		byte ADD = 1;

		/**
		 * 修改
		 */
		byte UPDATE = 2;
		
		/**
		 * 删除
		 */
		byte DEL = 3;
	}
	
}
