/*
 * 使用本软件请从杭州钛特云有限公司获取授权，其它途径获取本软件的行为皆为侵权行为
 * 本源代码由杭州钛特云科技有限公司授权给娄底大新土石方施工有限公司使用
 */package org.tio.sitexxx.service.model.main;

import java.util.Map;

import org.tio.sitexxx.service.model.main.base.BaseWxUserWithholdItem;
import org.tio.sitexxx.servicecommon.vo.PayConst;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WxUserWithholdItem extends BaseWxUserWithholdItem<WxUserWithholdItem> {
	public static final WxUserWithholdItem dao = new WxUserWithholdItem().dao();
	
	public Map<String, Object> toAllMap() {
		Map<String, Object> map = this._getAttrs();
		map.put(PayConst.ApiClassName.API_MAP_KEY,PayConst.ApiClassName.WITHHOLD_QUERY);
		return map;
	}
	
	public static WxUserWithholdItem toBean(Map<String, Object> map) {
		map.remove(PayConst.ApiClassName.API_MAP_KEY);
		WxUserWithholdItem withholdItem = new WxUserWithholdItem();
		withholdItem._setAttrs(map);
		return withholdItem;
	}
}
