package org.tio.sitexxx.service.model.main;

import org.tio.sitexxx.service.model.main.base.BaseYxCollect;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class YxCollect extends BaseYxCollect<YxCollect> {
	public static final YxCollect dao = new YxCollect().dao();
}
