package org.tio.sitexxx.service.model.main;

import org.tio.sitexxx.service.model.main.base.BaseYxOnekeyLoginTmp;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class YxOnekeyLoginTmp extends BaseYxOnekeyLoginTmp<YxOnekeyLoginTmp> {
	public static final YxOnekeyLoginTmp dao = new YxOnekeyLoginTmp().dao();
}
