package org.tio.sitexxx.service.model.main;

import org.tio.sitexxx.service.model.main.base.BaseYxUserWithdraw;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class YxUserWithdraw extends BaseYxUserWithdraw<YxUserWithdraw> {
	public static final YxUserWithdraw dao = new YxUserWithdraw().dao();
}
