package org.tio.sitexxx.service.model.main;

import org.tio.sitexxx.service.model.main.base.BaseYxUserSendRedPacket;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class YxUserSendRedPacket extends BaseYxUserSendRedPacket<YxUserSendRedPacket> {
	public static final YxUserSendRedPacket dao = new YxUserSendRedPacket().dao();
}
