package org.tio.sitexxx.service.model.main;

import org.tio.sitexxx.service.model.main.base.BaseYxUserWithdrawAccount;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class YxUserWithdrawAccount extends BaseYxUserWithdrawAccount<YxUserWithdrawAccount> {
	public static final YxUserWithdrawAccount dao = new YxUserWithdrawAccount().dao();
}
