package org.tio.sitexxx.service.model.main;

		import org.tio.sitexxx.service.model.main.base.BaseYxUserRecieverRedPacketItem;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class YxUserRecieverRedPacketItem extends BaseYxUserRecieverRedPacketItem<YxUserRecieverRedPacketItem> {
	public static final YxUserRecieverRedPacketItem dao = new YxUserRecieverRedPacketItem().dao();
}
