package org.tio.sitexxx.service.model.main;

import org.tio.sitexxx.service.model.main.base.BaseYxUserWalletItem;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class YxUserWalletItem extends BaseYxUserWalletItem<YxUserWalletItem> {
	public static final YxUserWalletItem dao = new YxUserWalletItem().dao();
}
