/*
 * 使用本软件请从杭州钛特云有限公司获取授权，其它途径获取本软件的行为皆为侵权行为
 * 本源代码由杭州钛特云科技有限公司授权给娄底大新土石方施工有限公司使用
 */package org.tio.mg.service.model.mg;

import org.tio.mg.service.model.mg.base.BaseMgInvoiceReimbursement;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MgInvoiceReimbursement extends BaseMgInvoiceReimbursement<MgInvoiceReimbursement> {
	public static final MgInvoiceReimbursement dao = new MgInvoiceReimbursement().dao();
	
	private Integer codeid;

	public Integer getCodeid() {
		return codeid;
	}

	public void setCodeid(Integer codeid) {
		this.codeid = codeid;
	}
}
