package org.tio.mg.service.model.mg;

import org.tio.mg.service.model.mg.base.BaseMgMenu;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MgMenu extends BaseMgMenu<MgMenu> {
	public static final MgMenu dao = new MgMenu().dao();

	private String parentName;

	private List<MgMenu> children;

	public String getParentName() {
		return parentName;
	}

	public void setParentName(String parentName) {
		this.parentName = parentName;
	}

	public List<MgMenu> getChildren() {
		return children;
	}

	public void setChildren(List<MgMenu> children) {
		this.children = children;
	}
}
