package org.tio.mg.service.model.mg;

import org.tio.mg.service.model.mg.base.BaseMgOperRecord;
import org.tio.mg.service.service.yxnxun.other.MgOperVo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MgOperRecord extends BaseMgOperRecord<MgOperRecord> {
	public static final MgOperRecord dao = new MgOperRecord().dao();

}
