package org.tio.mg.service.model.mg;

import org.tio.mg.service.model.mg.base.BaseMgRoleMenu;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MgRoleMenu extends BaseMgRoleMenu<MgRoleMenu> {
	public static final MgRoleMenu dao = new MgRoleMenu().dao();
}
