package org.tio.mg.service.model.mg;

import org.tio.mg.service.model.mg.base.BaseMguserLoginStat;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MguserLoginStat extends BaseMguserLoginStat<MguserLoginStat> {
	public static final MguserLoginStat dao = new MguserLoginStat().dao();
}
