package org.tio.mg.service.model.mg;

import org.tio.mg.service.model.mg.base.BaseMgUserLoginLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MgUserLoginLog extends BaseMgUserLoginLog<MgUserLoginLog> {
	public static final MgUserLoginLog dao = new MgUserLoginLog().dao();
}
