package org.tio.mg.service.model.mg;

import org.tio.mg.service.model.mg.base.BaseMgUserKey;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MgUserKey extends BaseMgUserKey<MgUserKey> {
	public static final MgUserKey dao = new MgUserKey().dao();
}
