package org.tio.mg.service.model.mg;

import org.tio.mg.service.model.mg.base.BaseMgUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MgUser extends BaseMgUser<MgUser> {
    public static final MgUser dao = new MgUser().dao();

    private Byte sex;

    private Integer rid;

    private String phone;

    private String email;

    private String realname;

    public Byte getSex() {
        return sex;
    }

    public void setSex(Byte sex) {
        this.sex = sex;
    }

    public Integer getRid() {
        return rid;
    }

    public void setRid(Integer rid) {
        this.rid = rid;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getRealname() {
        return realname;
    }

    public void setRealname(String realname) {
        this.realname = realname;
    }
}
