/*
 * 使用本软件请从杭州钛特云有限公司获取授权，其它途径获取本软件的行为皆为侵权行为
 * 本源代码由杭州钛特云科技有限公司授权给娄底大新土石方施工有限公司使用
 */
package org.tio.sitexxx.service.model.main.base;

import org.tio.sitexxx.service.jf.TioModel;
import org.tio.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseWxGroupMsgBak<M extends BaseWxGroupMsgBak<M>> extends TioModel<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	/**
	 * 模型：1：私聊；2：群聊
	 */
	public void setFrommode(java.lang.Byte frommode) {
		set("frommode", frommode);
	}
	
	/**
	 * 模型：1：私聊；2：群聊
	 */
	public java.lang.Byte getFrommode() {
		return getByte("frommode");
	}

	/**
	 * 转发消息来源
	 */
	public void setFrommsgid(java.lang.Long frommsgid) {
		set("frommsgid", frommsgid);
	}
	
	/**
	 * 转发消息来源
	 */
	public java.lang.Long getFrommsgid() {
		return getLong("frommsgid");
	}

	/**
	 * 聊天发起人uid
	 */
	public void setUid(java.lang.Integer uid) {
		set("uid", uid);
	}
	
	/**
	 * 聊天发起人uid
	 */
	public java.lang.Integer getUid() {
		return getInt("uid");
	}

	/**
	 * 聊天发起人的sessionid
	 */
	public void setSession(java.lang.String session) {
		set("session", session);
	}
	
	/**
	 * 聊天发起人的sessionid
	 */
	public java.lang.String getSession() {
		return getStr("session");
	}

	/**
	 * 聊天发起人所在的ip，ip_info的id字段
	 */
	public void setIpid(java.lang.Integer ipid) {
		set("ipid", ipid);
	}
	
	/**
	 * 聊天发起人所在的ip，ip_info的id字段
	 */
	public java.lang.Integer getIpid() {
		return getInt("ipid");
	}

	/**
	 * 主聊人员的设备类型（DeviceType），1：PC，2：安卓，3：IOS
	 */
	public void setDevice(java.lang.Byte device) {
		set("device", device);
	}
	
	/**
	 * 主聊人员的设备类型（DeviceType），1：PC，2：安卓，3：IOS
	 */
	public java.lang.Byte getDevice() {
		return getByte("device");
	}

	/**
	 * 群组id
	 */
	public void setGroupid(java.lang.Long groupid) {
		set("groupid", groupid);
	}
	
	/**
	 * 群组id
	 */
	public java.lang.Long getGroupid() {
		return getLong("groupid");
	}

	public void setResume(java.lang.String resume) {
		set("resume", resume);
	}
	
	public java.lang.String getResume() {
		return getStr("resume");
	}

	/**
	 * 聊天内容（原始内容）
	 */
	public void setText(java.lang.String text) {
		set("text", text);
	}
	
	/**
	 * 聊天内容（原始内容）
	 */
	public java.lang.String getText() {
		return getStr("text");
	}

	/**
	 * 聊天时间
	 */
	public void setTime(java.util.Date time) {
		set("time", time);
	}
	
	/**
	 * 聊天时间
	 */
	public java.util.Date getTime() {
		return get("time");
	}

	/**
	 * 附属业务id
	 */
	public void setBizid(java.lang.Long bizid) {
		set("bizid", bizid);
	}
	
	/**
	 * 附属业务id
	 */
	public java.lang.Long getBizid() {
		return getLong("bizid");
	}

	/**
	 * 内容类型，1、普通文本消息，2、超链接卡片消息，3、文件，4、音频，5、视频
	 */
	public void setContenttype(java.lang.Byte contenttype) {
		set("contenttype", contenttype);
	}
	
	/**
	 * 内容类型，1、普通文本消息，2、超链接卡片消息，3、文件，4、音频，5、视频
	 */
	public java.lang.Byte getContenttype() {
		return getByte("contenttype");
	}

	/**
	 * 这条消息的状态，1、正常、2、 自己撤回了，3、被管理员撤回
	 */
	public void setStatus(java.lang.Byte status) {
		set("status", status);
	}
	
	/**
	 * 这条消息的状态，1、正常、2、 自己撤回了，3、被管理员撤回
	 */
	public java.lang.Byte getStatus() {
		return getByte("status");
	}

	/**
	 * 该条消息是否由系统发出，譬如某某进入了群聊，1、系统发送；2、非系统发送
	 */
	public void setSendbysys(java.lang.Byte sendbysys) {
		set("sendbysys", sendbysys);
	}
	
	/**
	 * 该条消息是否由系统发出，譬如某某进入了群聊，1、系统发送；2、非系统发送
	 */
	public java.lang.Byte getSendbysys() {
		return getByte("sendbysys");
	}

	/**
	 * 归属单人的消息的用户
	 */
	public void setSigleuid(java.lang.Integer sigleuid) {
		set("sigleuid", sigleuid);
	}
	
	/**
	 * 归属单人的消息的用户
	 */
	public java.lang.Integer getSigleuid() {
		return getInt("sigleuid");
	}

	/**
	 * 是否是单通道消息：1：是；2：否
	 */
	public void setSigleflag(java.lang.Byte sigleflag) {
		set("sigleflag", sigleflag);
	}
	
	/**
	 * 是否是单通道消息：1：是；2：否
	 */
	public java.lang.Byte getSigleflag() {
		return getByte("sigleflag");
	}

	/**
	 * 过滤用户标识：1:是；2：否
	 */
	public void setWhereflag(java.lang.Byte whereflag) {
		set("whereflag", whereflag);
	}
	
	/**
	 * 过滤用户标识：1:是；2：否
	 */
	public java.lang.Byte getWhereflag() {
		return getByte("whereflag");
	}

	/**
	 * 过滤的用户uid,以头号分割
	 */
	public void setWhereuid(java.lang.String whereuid) {
		set("whereuid", whereuid);
	}
	
	/**
	 * 过滤的用户uid,以头号分割
	 */
	public java.lang.String getWhereuid() {
		return getStr("whereuid");
	}

	/**
	 * 记录创建时间
	 */
	public void setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
	}
	
	/**
	 * 记录创建时间
	 */
	public java.util.Date getCreatetime() {
		return get("createtime");
	}

	/**
	 * 记录更新时间
	 */
	public void setUpdatetime(java.util.Date updatetime) {
		set("updatetime", updatetime);
	}
	
	/**
	 * 记录更新时间
	 */
	public java.util.Date getUpdatetime() {
		return get("updatetime");
	}

	/**
	 * 备份时间：一般等于updatetime
	 */
	public void setBaktime(java.util.Date baktime) {
		set("baktime", baktime);
	}
	
	/**
	 * 备份时间：一般等于updatetime
	 */
	public java.util.Date getBaktime() {
		return get("baktime");
	}

}
