package org.tio.sitexxx.service.model.main.base;

import org.tio.sitexxx.service.jf.TioModel;
import org.tio.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseYxAdminRecieverAccount<M extends BaseYxAdminRecieverAccount<M>> extends TioModel<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
	}
	
	public java.util.Date getCreatetime() {
		return get("createtime");
	}

	public void setUpdatetime(java.util.Date updatetime) {
		set("updatetime", updatetime);
	}
	
	public java.util.Date getUpdatetime() {
		return get("updatetime");
	}

	/**
	 * 收款二维码
	 */
	public void setUrl(java.lang.String url) {
		set("url", url);
	}
	
	/**
	 * 收款二维码
	 */
	public java.lang.String getUrl() {
		return getStr("url");
	}

	/**
	 * 类型 1.微信 2.支付宝 3.银行卡
	 */
	public void setType(java.lang.Integer type) {
		set("type", type);
	}
	
	/**
	 * 类型 1.微信 2.支付宝 3.银行卡
	 */
	public java.lang.Integer getType() {
		return getInt("type");
	}

	/**
	 * 账户名称
	 */
	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	/**
	 * 账户名称
	 */
	public java.lang.String getName() {
		return getStr("name");
	}

	/**
	 * 支付宝或微信账号
	 */
	public void setPayno(java.lang.String payno) {
		set("payno", payno);
	}
	
	/**
	 * 支付宝或微信账号
	 */
	public java.lang.String getPayno() {
		return getStr("payno");
	}

	/**
	 * 银行卡号
	 */
	public void setBankcard(java.lang.String bankcard) {
		set("bankcard", bankcard);
	}
	
	/**
	 * 银行卡号
	 */
	public java.lang.String getBankcard() {
		return getStr("bankcard");
	}

	/**
	 * 开户银行名称
	 */
	public void setBankname(java.lang.String bankname) {
		set("bankname", bankname);
	}
	
	/**
	 * 开户银行名称
	 */
	public java.lang.String getBankname() {
		return getStr("bankname");
	}

	/**
	 * 账户状态0正常1冻结
	 */
	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}
	
	/**
	 * 账户状态0正常1冻结
	 */
	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	public void setExt1(java.lang.String ext1) {
		set("ext1", ext1);
	}
	
	public java.lang.String getExt1() {
		return getStr("ext1");
	}

	public void setExt2(java.lang.String ext2) {
		set("ext2", ext2);
	}
	
	public java.lang.String getExt2() {
		return getStr("ext2");
	}

	public void setExt3(java.lang.String ext3) {
		set("ext3", ext3);
	}
	
	public java.lang.String getExt3() {
		return getStr("ext3");
	}

}
