package org.tio.sitexxx.service.model.main.base;

import org.tio.sitexxx.service.jf.TioModel;
import org.tio.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUser<M extends BaseUser<M>> extends TioModel<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 用户个性化域名，方便访问者记忆
	 */
	public void setDomain(java.lang.String domain) {
		set("domain", domain);
	}
	
	/**
	 * 用户个性化域名，方便访问者记忆
	 */
	public java.lang.String getDomain() {
		return getStr("domain");
	}

	/**
	 * 登录名称
	 */
	public void setLoginname(java.lang.String loginname) {
		set("loginname", loginname);
	}
	
	/**
	 * 登录名称
	 */
	public java.lang.String getLoginname() {
		return getStr("loginname");
	}

	/**
	 * 邮箱
	 */
	public void setEmail(java.lang.String email) {
		set("email", email);
	}
	
	/**
	 * 邮箱
	 */
	public java.lang.String getEmail() {
		return getStr("email");
	}

	public void setPhone(java.lang.String phone) {
		set("phone", phone);
	}
	
	public java.lang.String getPhone() {
		return getStr("phone");
	}

	/**
	 * 原始密码
	 */
	public void setPwd(java.lang.String pwd) {
		set("pwd", pwd);
	}
	
	/**
	 * 原始密码
	 */
	public java.lang.String getPwd() {
		return getStr("pwd");
	}

	/**
	 * 手机密码
	 */
	public void setPhonepwd(java.lang.String phonepwd) {
		set("phonepwd", phonepwd);
	}
	
	/**
	 * 手机密码
	 */
	public java.lang.String getPhonepwd() {
		return getStr("phonepwd");
	}

	/**
	 * 邮箱密码
	 */
	public void setEmailpwd(java.lang.String emailpwd) {
		set("emailpwd", emailpwd);
	}
	
	/**
	 * 邮箱密码
	 */
	public java.lang.String getEmailpwd() {
		return getStr("emailpwd");
	}

	/**
	 * 等级
	 */
	public void setLevel(java.lang.Integer level) {
		set("level", level);
	}
	
	/**
	 * 等级
	 */
	public java.lang.Integer getLevel() {
		return getInt("level");
	}

	public void setViplevel(java.lang.Integer viplevel) {
		set("viplevel", viplevel);
	}
	
	public java.lang.Integer getViplevel() {
		return getInt("viplevel");
	}

	/**
	 * 邀请码
	 */
	public void setInvitecode(java.lang.String invitecode) {
		set("invitecode", invitecode);
	}
	
	/**
	 * 邀请码
	 */
	public java.lang.String getInvitecode() {
		return getStr("invitecode");
	}

	/**
	 * 昵称
	 */
	public void setNick(java.lang.String nick) {
		set("nick", nick);
	}
	
	/**
	 * 昵称
	 */
	public java.lang.String getNick() {
		return getStr("nick");
	}

	/**
	 * 头像url
	 */
	public void setAvatar(java.lang.String avatar) {
		set("avatar", avatar);
	}
	
	/**
	 * 头像url
	 */
	public java.lang.String getAvatar() {
		return getStr("avatar");
	}

	/**
	 * 头像说明
	 */
	public void setAvatarbig(java.lang.String avatarbig) {
		set("avatarbig", avatarbig);
	}
	
	/**
	 * 头像说明
	 */
	public java.lang.String getAvatarbig() {
		return getStr("avatarbig");
	}

	/**
	 * 注册ip
	 */
	public void setIpid(java.lang.Integer ipid) {
		set("ipid", ipid);
	}
	
	/**
	 * 注册ip
	 */
	public java.lang.Integer getIpid() {
		return getInt("ipid");
	}

	/**
	 * 允许被搜索的标识：1：是；2：否
	 */
	public void setSearchflag(java.lang.Byte searchflag) {
		set("searchflag", searchflag);
	}
	
	/**
	 * 允许被搜索的标识：1：是；2：否
	 */
	public java.lang.Byte getSearchflag() {
		return getByte("searchflag");
	}

	/**
	 * 消息总提醒标识：1：是；2：否
	 */
	public void setMsgremindflag(java.lang.Byte msgremindflag) {
		set("msgremindflag", msgremindflag);
	}
	
	/**
	 * 消息总提醒标识：1：是；2：否
	 */
	public java.lang.Byte getMsgremindflag() {
		return getByte("msgremindflag");
	}

	/**
	 * 是否好友验证：1：是；2：否
	 */
	public void setFdvalidtype(java.lang.Byte fdvalidtype) {
		set("fdvalidtype", fdvalidtype);
	}
	
	/**
	 * 是否好友验证：1：是；2：否
	 */
	public java.lang.Byte getFdvalidtype() {
		return getByte("fdvalidtype");
	}

	/**
	 * 三方登录状态：1：正式（非三方登录）；2：初创
	 */
	public void setThirdstatus(java.lang.Byte thirdstatus) {
		set("thirdstatus", thirdstatus);
	}
	
	/**
	 * 三方登录状态：1：正式（非三方登录）；2：初创
	 */
	public java.lang.Byte getThirdstatus() {
		return getByte("thirdstatus");
	}

	/**
	 * 第三方登录类型：1、PC版QQ，2、微信，3、微博，11、移动版QQ、22、移动版微信 33、移动版微博
	 */
	public void setThirdtype(java.lang.Integer thirdtype) {
		set("thirdtype", thirdtype);
	}
	
	/**
	 * 第三方登录类型：1、PC版QQ，2、微信，3、微博，11、移动版QQ、22、移动版微信 33、移动版微博
	 */
	public java.lang.Integer getThirdtype() {
		return getInt("thirdtype");
	}

	/**
	 * 类型：1：pc;2:安卓；3：ios
	 */
	public void setRegistertype(java.lang.Byte registertype) {
		set("registertype", registertype);
	}
	
	/**
	 * 类型：1：pc;2:安卓；3：ios
	 */
	public java.lang.Byte getRegistertype() {
		return getByte("registertype");
	}

	/**
	 * 禁言标识：1：是；2：否
	 */
	public void setMsgforbiddenflag(java.lang.Byte msgforbiddenflag) {
		set("msgforbiddenflag", msgforbiddenflag);
	}
	
	/**
	 * 禁言标识：1：是；2：否
	 */
	public java.lang.Byte getMsgforbiddenflag() {
		return getByte("msgforbiddenflag");
	}

	/**
	 * 手机绑定状态：1：是；2：否
	 */
	public void setPhonebindflag(java.lang.Byte phonebindflag) {
		set("phonebindflag", phonebindflag);
	}
	
	/**
	 * 手机绑定状态：1：是；2：否
	 */
	public java.lang.Byte getPhonebindflag() {
		return getByte("phonebindflag");
	}

	/**
	 * 邮箱绑定状态：1：是；2：否
	 */
	public void setEmailbindflag(java.lang.Byte emailbindflag) {
		set("emailbindflag", emailbindflag);
	}
	
	/**
	 * 邮箱绑定状态：1：是；2：否
	 */
	public java.lang.Byte getEmailbindflag() {
		return getByte("emailbindflag");
	}

	/**
	 * 三方绑定状态：1：是；2：否
	 */
	public void setThirdbindflag(java.lang.Byte thirdbindflag) {
		set("thirdbindflag", thirdbindflag);
	}
	
	/**
	 * 三方绑定状态：1：是；2：否
	 */
	public java.lang.Byte getThirdbindflag() {
		return getByte("thirdbindflag");
	}

	/**
	 * 开户状态：1：开户；2：未开户
	 */
	public void setOpenflag(java.lang.Byte openflag) {
		set("openflag", openflag);
	}
	
	/**
	 * 开户状态：1：开户；2：未开户
	 */
	public java.lang.Byte getOpenflag() {
		return getByte("openflag");
	}

	/**
	 * 开户id
	 */
	public void setOpenid(java.lang.Integer openid) {
		set("openid", openid);
	}
	
	/**
	 * 开户id
	 */
	public java.lang.Integer getOpenid() {
		return getInt("openid");
	}

	/**
	 * 注册页面
	 */
	public void setReghref(java.lang.String reghref) {
		set("reghref", reghref);
	}
	
	/**
	 * 注册页面
	 */
	public java.lang.String getReghref() {
		return getStr("reghref");
	}

	/**
	 * 机器人标识：1:是；2：否
	 */
	public void setXx(java.lang.Byte xx) {
		set("xx", xx);
	}
	
	/**
	 * 机器人标识：1:是；2：否
	 */
	public java.lang.Byte getXx() {
		return getByte("xx");
	}

	/**
	 * 备注
	 */
	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}
	
	/**
	 * 备注
	 */
	public java.lang.String getRemark() {
		return getStr("remark");
	}

	/**
	 * 用户状态, 1：正常，2：未激活；3：违规，4：封停，5：注销
	 */
	public void setStatus(java.lang.Byte status) {
		set("status", status);
	}
	
	/**
	 * 用户状态, 1：正常，2：未激活；3：违规，4：封停，5：注销
	 */
	public java.lang.Byte getStatus() {
		return getByte("status");
	}

	/**
	 * 创建时间
	 */
	public void setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreatetime() {
		return get("createtime");
	}

	/**
	 * 修改时间
	 */
	public void setUpdatetime(java.util.Date updatetime) {
		set("updatetime", updatetime);
	}
	
	/**
	 * 修改时间
	 */
	public java.util.Date getUpdatetime() {
		return get("updatetime");
	}

}
