package org.tio.sitexxx.service.model.main.base;

import org.tio.sitexxx.service.jf.TioModel;
import org.tio.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseYxUserRecieverRedPacketItem<M extends BaseYxUserRecieverRedPacketItem<M>> extends TioModel<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 记录创建时间
	 */
	public void setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
	}
	
	/**
	 * 记录创建时间
	 */
	public java.util.Date getCreatetime() {
		return get("createtime");
	}

	/**
	 * 该记录更新时间
	 */
	public void setUpdatetime(java.util.Date updatetime) {
		set("updatetime", updatetime);
	}
	
	/**
	 * 该记录更新时间
	 */
	public java.util.Date getUpdatetime() {
		return get("updatetime");
	}

	/**
	 * 红包ID
	 */
	public void setRedid(java.lang.Integer redid) {
		set("redid", redid);
	}
	
	/**
	 * 红包ID
	 */
	public java.lang.Integer getRedid() {
		return getInt("redid");
	}

	/**
	 * 收红包的uid
	 */
	public void setUid(java.lang.Integer uid) {
		set("uid", uid);
	}
	
	/**
	 * 收红包的uid
	 */
	public java.lang.Integer getUid() {
		return getInt("uid");
	}

	/**
	 * 领取到的金额
	 */
	public void setMoney(java.lang.Integer money) {
		set("money", money);
	}
	
	/**
	 * 领取到的金额
	 */
	public java.lang.Integer getMoney() {
		return getInt("money");
	}

	/**
	 * 1正常红包2红包退回
	 */
	public void setType(java.lang.Integer type) {
		set("type", type);
	}
	
	/**
	 * 1正常红包2红包退回
	 */
	public java.lang.Integer getType() {
		return getInt("type");
	}

	/**
	 * 备注
	 */
	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}
	
	/**
	 * 备注
	 */
	public java.lang.String getRemark() {
		return getStr("remark");
	}

	public void setExt1(java.lang.String ext1) {
		set("ext1", ext1);
	}
	
	public java.lang.String getExt1() {
		return getStr("ext1");
	}

	public void setExt2(java.lang.String ext2) {
		set("ext2", ext2);
	}
	
	public java.lang.String getExt2() {
		return getStr("ext2");
	}

	public void setExt3(java.lang.String ext3) {
		set("ext3", ext3);
	}
	
	public java.lang.String getExt3() {
		return getStr("ext3");
	}

}
