package org.tio.sitexxx.service.model.main.base;

import org.tio.sitexxx.service.jf.TioModel;
import org.tio.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseWxGroup<M extends BaseWxGroup<M>> extends TioModel<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	/**
	 * 群名称
	 */
	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	/**
	 * 群名称
	 */
	public java.lang.String getName() {
		return getStr("name");
	}

	/**
	 *  群主的userid
	 */
	public void setUid(java.lang.Integer uid) {
		set("uid", uid);
	}
	
	/**
	 *  群主的userid
	 */
	public java.lang.Integer getUid() {
		return getInt("uid");
	}

	/**
	 * 进群方式：1、群主审核；2：非审核
	 */
	public void setJoinmode(java.lang.Byte joinmode) {
		set("joinmode", joinmode);
	}
	
	/**
	 * 进群方式：1、群主审核；2：非审核
	 */
	public java.lang.Byte getJoinmode() {
		return getByte("joinmode");
	}

	/**
	 * 好友开关：1：开启；2：不开启
	 */
	public void setFriendflag(java.lang.Byte friendflag) {
		set("friendflag", friendflag);
	}
	
	/**
	 * 好友开关：1：开启；2：不开启
	 */
	public java.lang.Byte getFriendflag() {
		return getByte("friendflag");
	}

	/**
	 * 邀请开关：1：开启；2：非开启
	 */
	public void setApplyflag(java.lang.Byte applyflag) {
		set("applyflag", applyflag);
	}
	
	/**
	 * 邀请开关：1：开启；2：非开启
	 */
	public java.lang.Byte getApplyflag() {
		return getByte("applyflag");
	}

	/**
	 * 普通成员退群开关：1：开启 2：不开启
	 */
	public void setExitflag(java.lang.Byte exitflag) {
		set("exitflag", exitflag);
	}
	
	/**
	 * 普通成员退群开关：1：开启 2：不开启
	 */
	public java.lang.Byte getExitflag() {
		return getByte("exitflag");
	}

	/**
	 * 是否进行消息激活群：1：是；2：否
	 */
	public void setMsgactflag(java.lang.Byte msgactflag) {
		set("msgactflag", msgactflag);
	}
	
	/**
	 * 是否进行消息激活群：1：是；2：否
	 */
	public java.lang.Byte getMsgactflag() {
		return getByte("msgactflag");
	}

	/**
	 * 群头像
	 */
	public void setAvatar(java.lang.String avatar) {
		set("avatar", avatar);
	}
	
	/**
	 * 群头像
	 */
	public java.lang.String getAvatar() {
		return getStr("avatar");
	}

	/**
	 * 群公告
	 */
	public void setNotice(java.lang.String notice) {
		set("notice", notice);
	}
	
	/**
	 * 群公告
	 */
	public java.lang.String getNotice() {
		return getStr("notice");
	}

	/**
	 * 公告时间
	 */
	public void setNoticetime(java.util.Date noticetime) {
		set("noticetime", noticetime);
	}
	
	/**
	 * 公告时间
	 */
	public java.util.Date getNoticetime() {
		return get("noticetime");
	}

	/**
	 * 当前群的状态：1、正常；2、被封；3、群主删除
	 */
	public void setStatus(java.lang.Byte status) {
		set("status", status);
	}
	
	/**
	 * 当前群的状态：1、正常；2、被封；3、群主删除
	 */
	public java.lang.Byte getStatus() {
		return getByte("status");
	}

	/**
	 * 头像自动生成标志：1：是；2：否
	 */
	public void setAutoflag(java.lang.Byte autoflag) {
		set("autoflag", autoflag);
	}
	
	/**
	 * 头像自动生成标志：1：是；2：否
	 */
	public java.lang.Byte getAutoflag() {
		return getByte("autoflag");
	}

	/**
	 * 头像自动生成标识：1：是；2：否
	 */
	public void setAvatarautoflag(java.lang.Byte avatarautoflag) {
		set("avatarautoflag", avatarautoflag);
	}
	
	/**
	 * 头像自动生成标识：1：是；2：否
	 */
	public java.lang.Byte getAvatarautoflag() {
		return getByte("avatarautoflag");
	}

	/**
	 * 群简介
	 */
	public void setIntro(java.lang.String intro) {
		set("intro", intro);
	}
	
	/**
	 * 群简介
	 */
	public java.lang.String getIntro() {
		return getStr("intro");
	}

	/**
	 *  群创建时间
	 */
	public void setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
	}
	
	/**
	 *  群创建时间
	 */
	public java.util.Date getCreatetime() {
		return get("createtime");
	}

	/**
	 *  群资料更新时间
	 */
	public void setUpdatetime(java.util.Date updatetime) {
		set("updatetime", updatetime);
	}
	
	/**
	 *  群资料更新时间
	 */
	public java.util.Date getUpdatetime() {
		return get("updatetime");
	}

}
