package org.tio.sitexxx.service.model.main.base;

import org.tio.sitexxx.service.jf.TioModel;
import org.tio.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseYxTransAccounts<M extends BaseYxTransAccounts<M>> extends TioModel<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 记录创建时间
	 */
	public void setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
	}
	
	/**
	 * 记录创建时间
	 */
	public java.util.Date getCreatetime() {
		return get("createtime");
	}

	/**
	 * 该记录更新时间
	 */
	public void setUpdatetime(java.util.Date updatetime) {
		set("updatetime", updatetime);
	}
	
	/**
	 * 该记录更新时间
	 */
	public java.util.Date getUpdatetime() {
		return get("updatetime");
	}

	public void setFromUid(java.lang.Integer fromUid) {
		set("from_uid", fromUid);
	}
	
	public java.lang.Integer getFromUid() {
		return getInt("from_uid");
	}

	public void setFromNick(java.lang.String fromNick) {
		set("from_nick", fromNick);
	}
	
	public java.lang.String getFromNick() {
		return getStr("from_nick");
	}

	public void setToUid(java.lang.Integer toUid) {
		set("to_uid", toUid);
	}
	
	public java.lang.Integer getToUid() {
		return getInt("to_uid");
	}

	public void setToNick(java.lang.String toNick) {
		set("to_nick", toNick);
	}
	
	public java.lang.String getToNick() {
		return getStr("to_nick");
	}

	/**
	 * 金额：分
	 */
	public void setAmount(java.lang.Integer amount) {
		set("amount", amount);
	}
	
	/**
	 * 金额：分
	 */
	public java.lang.Integer getAmount() {
		return getInt("amount");
	}

	/**
	 * 状态：0-创建转账未支付 1-转出未接收 2-已接收 4-过期退还5-直接退还
	 */
	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}
	
	/**
	 * 状态：0-创建转账未支付 1-转出未接收 2-已接收 4-过期退还5-直接退还
	 */
	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	/**
	 * 流水号
	 */
	public void setSerial(java.lang.String serial) {
		set("serial", serial);
	}
	
	/**
	 * 流水号
	 */
	public java.lang.String getSerial() {
		return getStr("serial");
	}

	/**
	 * 接收时间
	 */
	public void setRecievertime(java.util.Date recievertime) {
		set("recievertime", recievertime);
	}
	
	/**
	 * 接收时间
	 */
	public java.util.Date getRecievertime() {
		return get("recievertime");
	}

	/**
	 * 退还时间
	 */
	public void setBacktime(java.util.Date backtime) {
		set("backtime", backtime);
	}
	
	/**
	 * 退还时间
	 */
	public java.util.Date getBacktime() {
		return get("backtime");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}
	
	public java.lang.String getRemark() {
		return getStr("remark");
	}

	public void setExt1(java.lang.String ext1) {
		set("ext1", ext1);
	}
	
	public java.lang.String getExt1() {
		return getStr("ext1");
	}

	public void setExt2(java.lang.String ext2) {
		set("ext2", ext2);
	}
	
	public java.lang.String getExt2() {
		return getStr("ext2");
	}

	public void setExt3(java.lang.String ext3) {
		set("ext3", ext3);
	}
	
	public java.lang.String getExt3() {
		return getStr("ext3");
	}

}
