/*
 * 使用本软件请从杭州钛特云有限公司获取授权，其它途径获取本软件的行为皆为侵权行为
 * 本源代码由杭州钛特云科技有限公司授权给娄底大新土石方施工有限公司使用
 */
package org.tio.sitexxx.service.model.main.base;

import org.tio.sitexxx.service.jf.TioModel;
import org.tio.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseWxGroupUserBak<M extends BaseWxGroupUserBak<M>> extends TioModel<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	/**
	 * im_group的id
	 */
	public void setGroupid(java.lang.Long groupid) {
		set("groupid", groupid);
	}
	
	/**
	 * im_group的id
	 */
	public java.lang.Long getGroupid() {
		return getLong("groupid");
	}

	public void setUid(java.lang.Integer uid) {
		set("uid", uid);
	}
	
	public java.lang.Integer getUid() {
		return getInt("uid");
	}

	/**
	 * 该用户在群内的昵称
	 */
	public void setGroupnick(java.lang.String groupnick) {
		set("groupnick", groupnick);
	}
	
	/**
	 * 该用户在群内的昵称
	 */
	public java.lang.String getGroupnick() {
		return getStr("groupnick");
	}

	/**
	 * 从哪个消息开始有阅读权限
	 */
	public void setStartmsgid(java.lang.Long startmsgid) {
		set("startmsgid", startmsgid);
	}
	
	/**
	 * 从哪个消息开始有阅读权限
	 */
	public java.lang.Long getStartmsgid() {
		return getLong("startmsgid");
	}

	/**
	 * 注意：废弃字段,如果使用，请放入动态表中:该用户最后一次收到的消息id，对应im_group_msg的id
	 */
	public void setLastmsgid(java.lang.Long lastmsgid) {
		set("lastmsgid", lastmsgid);
	}
	
	/**
	 * 注意：废弃字段,如果使用，请放入动态表中:该用户最后一次收到的消息id，对应im_group_msg的id
	 */
	public java.lang.Long getLastmsgid() {
		return getLong("lastmsgid");
	}

	/**
	 * 显示状态：1：正常；2：未消息激活；3：列表删除
	 */
	public void setViewstatus(java.lang.Byte viewstatus) {
		set("viewstatus", viewstatus);
	}
	
	/**
	 * 显示状态：1：正常；2：未消息激活；3：列表删除
	 */
	public java.lang.Byte getViewstatus() {
		return getByte("viewstatus");
	}

	/**
	 * 是否加入通讯录：1：是；2：否
	 */
	public void setIsaddress(java.lang.Byte isaddress) {
		set("isaddress", isaddress);
	}
	
	/**
	 * 是否加入通讯录：1：是；2：否
	 */
	public java.lang.Byte getIsaddress() {
		return getByte("isaddress");
	}

	/**
	 * 是否免打扰：1：是；2：否
	 */
	public void setMsgfreeflag(java.lang.Byte msgfreeflag) {
		set("msgfreeflag", msgfreeflag);
	}
	
	/**
	 * 是否免打扰：1：是；2：否
	 */
	public java.lang.Byte getMsgfreeflag() {
		return getByte("msgfreeflag");
	}

	/**
	 * 是否显示昵称：1：是；2：否
	 */
	public void setNickviewflag(java.lang.Byte nickviewflag) {
		set("nickviewflag", nickviewflag);
	}
	
	/**
	 * 是否显示昵称：1：是；2：否
	 */
	public java.lang.Byte getNickviewflag() {
		return getByte("nickviewflag");
	}

	/**
	 * 群角色：1：群主；2：成员
	 */
	public void setGrouprole(java.lang.Byte grouprole) {
		set("grouprole", grouprole);
	}
	
	/**
	 * 群角色：1：群主；2：成员
	 */
	public java.lang.Byte getGrouprole() {
		return getByte("grouprole");
	}

	/**
	 * 状态：1：正常；2：退群
	 */
	public void setStatus(java.lang.Byte status) {
		set("status", status);
	}
	
	/**
	 * 状态：1：正常；2：退群
	 */
	public java.lang.Byte getStatus() {
		return getByte("status");
	}

	/**
	 * 记录创建时间
	 */
	public void setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
	}
	
	/**
	 * 记录创建时间
	 */
	public java.util.Date getCreatetime() {
		return get("createtime");
	}

	/**
	 * 该记录更新时间
	 */
	public void setUpdatetime(java.util.Date updatetime) {
		set("updatetime", updatetime);
	}
	
	/**
	 * 该记录更新时间
	 */
	public java.util.Date getUpdatetime() {
		return get("updatetime");
	}

	/**
	 * 备份时间：一般等于updatetime
	 */
	public void setBaktime(java.util.Date baktime) {
		set("baktime", baktime);
	}
	
	/**
	 * 备份时间：一般等于updatetime
	 */
	public java.util.Date getBaktime() {
		return get("baktime");
	}

}
