/*
 * 使用本软件请从杭州钛特云有限公司获取授权，其它途径获取本软件的行为皆为侵权行为
 * 本源代码由杭州钛特云科技有限公司授权给娄底大新土石方施工有限公司使用
 */
package org.tio.sitexxx.service.model.main.base;

import org.tio.sitexxx.service.jf.TioModel;
import org.tio.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseWxFriendBak<M extends BaseWxFriendBak<M>> extends TioModel<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	/**
	 * 主人的userid
	 */
	public void setUid(java.lang.Integer uid) {
		set("uid", uid);
	}
	
	/**
	 * 主人的userid
	 */
	public java.lang.Integer getUid() {
		return getInt("uid");
	}

	/**
	 * 好友的userid
	 */
	public void setFrienduid(java.lang.Integer frienduid) {
		set("frienduid", frienduid);
	}
	
	/**
	 * 好友的userid
	 */
	public java.lang.Integer getFrienduid() {
		return getInt("frienduid");
	}

	/**
	 * 备注名
	 */
	public void setRemarkname(java.lang.String remarkname) {
		set("remarkname", remarkname);
	}
	
	/**
	 * 备注名
	 */
	public java.lang.String getRemarkname() {
		return getStr("remarkname");
	}

	/**
	 * 电话
	 */
	public void setPhone(java.lang.String phone) {
		set("phone", phone);
	}
	
	/**
	 * 电话
	 */
	public java.lang.String getPhone() {
		return getStr("phone");
	}

	/**
	 * 其他备注
	 */
	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}
	
	/**
	 * 其他备注
	 */
	public java.lang.String getRemark() {
		return getStr("remark");
	}

	/**
	 * 状态：1：好友
	 */
	public void setStatus(java.lang.Byte status) {
		set("status", status);
	}
	
	/**
	 * 状态：1：好友
	 */
	public java.lang.Byte getStatus() {
		return getByte("status");
	}

	/**
	 * 从哪个消息开始有阅读权限
	 */
	public void setStartmsgid(java.lang.Long startmsgid) {
		set("startmsgid", startmsgid);
	}
	
	/**
	 * 从哪个消息开始有阅读权限
	 */
	public java.lang.Long getStartmsgid() {
		return getLong("startmsgid");
	}

	/**
	 * 是否免打扰：1：是；2：否
	 */
	public void setMsgfreeflag(java.lang.Byte msgfreeflag) {
		set("msgfreeflag", msgfreeflag);
	}
	
	/**
	 * 是否免打扰：1：是；2：否
	 */
	public java.lang.Byte getMsgfreeflag() {
		return getByte("msgfreeflag");
	}

	/**
	 * 字母排序
	 */
	public void setChatindex(java.lang.String chatindex) {
		set("chatindex", chatindex);
	}
	
	/**
	 * 字母排序
	 */
	public java.lang.String getChatindex() {
		return getStr("chatindex");
	}

	/**
	 * 更新时间
	 */
	public void setUpdatetime(java.util.Date updatetime) {
		set("updatetime", updatetime);
	}
	
	/**
	 * 更新时间
	 */
	public java.util.Date getUpdatetime() {
		return get("updatetime");
	}

	/**
	 * 创建时间
	 */
	public void setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreatetime() {
		return get("createtime");
	}

	/**
	 * 备份时间
	 */
	public void setBaktime(java.util.Date baktime) {
		set("baktime", baktime);
	}
	
	/**
	 * 备份时间
	 */
	public java.util.Date getBaktime() {
		return get("baktime");
	}

}
