package org.tio.sitexxx.service.model.main.base;

import org.tio.sitexxx.service.jf.TioModel;
import org.tio.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseWxUserCoin<M extends BaseWxUserCoin<M>> extends TioModel<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 用户id
	 */
	public void setUid(java.lang.Integer uid) {
		set("uid", uid);
	}
	
	/**
	 * 用户id
	 */
	public java.lang.Integer getUid() {
		return getInt("uid");
	}

	/**
	 * 钱包余额
	 */
	public void setCny(java.lang.Double cny) {
		set("cny", cny);
	}
	
	/**
	 * 钱包余额
	 */
	public java.lang.Double getCny() {
		return getDouble("cny");
	}

	/**
	 * 体现余额
	 */
	public void setWithdrawcny(java.lang.Double withdrawcny) {
		set("withdrawcny", withdrawcny);
	}
	
	/**
	 * 体现余额
	 */
	public java.lang.Double getWithdrawcny() {
		return getDouble("withdrawcny");
	}

	/**
	 * 接受红包
	 */
	public void setAcceptredpacket(java.lang.Double acceptredpacket) {
		set("acceptredpacket", acceptredpacket);
	}
	
	/**
	 * 接受红包
	 */
	public java.lang.Double getAcceptredpacket() {
		return getDouble("acceptredpacket");
	}

	/**
	 * 发送红包
	 */
	public void setSendpacket(java.lang.Double sendpacket) {
		set("sendpacket", sendpacket);
	}
	
	/**
	 * 发送红包
	 */
	public java.lang.Double getSendpacket() {
		return getDouble("sendpacket");
	}

	/**
	 * 消费密码
	 */
	public void setCostpwd(java.lang.String costpwd) {
		set("costpwd", costpwd);
	}
	
	/**
	 * 消费密码
	 */
	public java.lang.String getCostpwd() {
		return getStr("costpwd");
	}

	/**
	 * 记录创建时间
	 */
	public void setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
	}
	
	/**
	 * 记录创建时间
	 */
	public java.util.Date getCreatetime() {
		return get("createtime");
	}

	/**
	 * 该记录更新时间
	 */
	public void setUpdatetime(java.util.Date updatetime) {
		set("updatetime", updatetime);
	}
	
	/**
	 * 该记录更新时间
	 */
	public java.util.Date getUpdatetime() {
		return get("updatetime");
	}

}
