/*
 * 使用本软件请从杭州钛特云有限公司获取授权，其它途径获取本软件的行为皆为侵权行为
 * 本源代码由杭州钛特云科技有限公司授权给娄底大新土石方施工有限公司使用
 */
package org.tio.sitexxx.service.model.main.base;

import org.tio.sitexxx.service.jf.TioModel;
import org.tio.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseWxFriendMsgBak<M extends BaseWxFriendMsgBak<M>> extends TioModel<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	/**
	 * 转发消息来源
	 */
	public void setFrommsgid(java.lang.Long frommsgid) {
		set("frommsgid", frommsgid);
	}
	
	/**
	 * 转发消息来源
	 */
	public java.lang.Long getFrommsgid() {
		return getLong("frommsgid");
	}

	/**
	 * 聊天发起人，user表的id
	 */
	public void setUid(java.lang.Integer uid) {
		set("uid", uid);
	}
	
	/**
	 * 聊天发起人，user表的id
	 */
	public java.lang.Integer getUid() {
		return getInt("uid");
	}

	/**
	 * 聊天发起人的sessionid
	 */
	public void setSession(java.lang.String session) {
		set("session", session);
	}
	
	/**
	 * 聊天发起人的sessionid
	 */
	public java.lang.String getSession() {
		return getStr("session");
	}

	/**
	 * 私聊时，会有值，表示是和谁私聊。此值为null表示是群聊
	 */
	public void setTouid(java.lang.Integer touid) {
		set("touid", touid);
	}
	
	/**
	 * 私聊时，会有值，表示是和谁私聊。此值为null表示是群聊
	 */
	public java.lang.Integer getTouid() {
		return getInt("touid");
	}

	/**
	 * 私聊时，会有值，表示是和谁私聊。此值为null表示是群聊
	 */
	public void setTosession(java.lang.String tosession) {
		set("tosession", tosession);
	}
	
	/**
	 * 私聊时，会有值，表示是和谁私聊。此值为null表示是群聊
	 */
	public java.lang.String getTosession() {
		return getStr("tosession");
	}

	/**
	 * 反向发送标识(接收者触发发送)：1：是；2：否
	 */
	public void setReverseflag(java.lang.Byte reverseflag) {
		set("reverseflag", reverseflag);
	}
	
	/**
	 * 反向发送标识(接收者触发发送)：1：是；2：否
	 */
	public java.lang.Byte getReverseflag() {
		return getByte("reverseflag");
	}

	/**
	 * 归属单人的消息的用户
	 */
	public void setSigleuid(java.lang.Integer sigleuid) {
		set("sigleuid", sigleuid);
	}
	
	/**
	 * 归属单人的消息的用户
	 */
	public java.lang.Integer getSigleuid() {
		return getInt("sigleuid");
	}

	/**
	 * 是否是单通道消息：1：是；2：否
	 */
	public void setSigleflag(java.lang.Byte sigleflag) {
		set("sigleflag", sigleflag);
	}
	
	/**
	 * 是否是单通道消息：1：是；2：否
	 */
	public java.lang.Byte getSigleflag() {
		return getByte("sigleflag");
	}

	/**
	 * 聊天发起人所在的ip，ip_info的id字段
	 */
	public void setIpid(java.lang.Integer ipid) {
		set("ipid", ipid);
	}
	
	/**
	 * 聊天发起人所在的ip，ip_info的id字段
	 */
	public java.lang.Integer getIpid() {
		return getInt("ipid");
	}

	/**
	 * 主聊人员的设备类型（DeviceType），1：PC，2：安卓，3：IOS
	 */
	public void setDevice(java.lang.Byte device) {
		set("device", device);
	}
	
	/**
	 * 主聊人员的设备类型（DeviceType），1：PC，2：安卓，3：IOS
	 */
	public java.lang.Byte getDevice() {
		return getByte("device");
	}

	/**
	 * 聊天内容（原始内容）
	 */
	public void setText(java.lang.String text) {
		set("text", text);
	}
	
	/**
	 * 聊天内容（原始内容）
	 */
	public java.lang.String getText() {
		return getStr("text");
	}

	/**
	 * 缩略文字
	 */
	public void setResume(java.lang.String resume) {
		set("resume", resume);
	}
	
	/**
	 * 缩略文字
	 */
	public java.lang.String getResume() {
		return getStr("resume");
	}

	/**
	 * 聊天时间
	 */
	public void setTime(java.util.Date time) {
		set("time", time);
	}
	
	/**
	 * 聊天时间
	 */
	public java.util.Date getTime() {
		return get("time");
	}

	/**
	 * 该条消息是否由系统发出，譬如添加好友通知、评论通知等

1：是由系统发出的
2：非系统发出
	 */
	public void setSendbysys(java.lang.Byte sendbysys) {
		set("sendbysys", sendbysys);
	}
	
	/**
	 * 该条消息是否由系统发出，譬如添加好友通知、评论通知等

1：是由系统发出的
2：非系统发出
	 */
	public java.lang.Byte getSendbysys() {
		return getByte("sendbysys");
	}

	/**
	 * 消息类型：1：正常消息：2：操作消息
	 */
	public void setMsgtype(java.lang.Byte msgtype) {
		set("msgtype", msgtype);
	}
	
	/**
	 * 消息类型：1：正常消息：2：操作消息
	 */
	public java.lang.Byte getMsgtype() {
		return getByte("msgtype");
	}

	/**
	 * 操作码：1：删除聊天会话；2：拉黑；3：恢复拉黑
	 */
	public void setOper(java.lang.Byte oper) {
		set("oper", oper);
	}
	
	/**
	 * 操作码：1：删除聊天会话；2：拉黑；3：恢复拉黑
	 */
	public java.lang.Byte getOper() {
		return getByte("oper");
	}

	/**
	 * 内容类型，1、普通文本消息，2、超链接卡片消息，3、文件，4、音频，5、视频
	 */
	public void setContenttype(java.lang.Byte contenttype) {
		set("contenttype", contenttype);
	}
	
	/**
	 * 内容类型，1、普通文本消息，2、超链接卡片消息，3、文件，4、音频，5、视频
	 */
	public java.lang.Byte getContenttype() {
		return getByte("contenttype");
	}

	/**
	 * 这条消息的状态，1、正常、2、 自己撤回了，3、被管理员撤回
	 */
	public void setStatus(java.lang.Byte status) {
		set("status", status);
	}
	
	/**
	 * 这条消息的状态，1、正常、2、 自己撤回了，3、被管理员撤回
	 */
	public java.lang.Byte getStatus() {
		return getByte("status");
	}

	/**
	 * 已读标识。1：已读，2：未读
	 */
	public void setReadflag(java.lang.Byte readflag) {
		set("readflag", readflag);
	}
	
	/**
	 * 已读标识。1：已读，2：未读
	 */
	public java.lang.Byte getReadflag() {
		return getByte("readflag");
	}

	/**
	 * 对方阅读消息的时间
	 */
	public void setReadtime(java.util.Date readtime) {
		set("readtime", readtime);
	}
	
	/**
	 * 对方阅读消息的时间
	 */
	public java.util.Date getReadtime() {
		return get("readtime");
	}

	/**
	 * 主聊人员的设备类型（DeviceType），1：PC，2：安卓，3：IOS
	 */
	public void setReaddevice(java.lang.Byte readdevice) {
		set("readdevice", readdevice);
	}
	
	/**
	 * 主聊人员的设备类型（DeviceType），1：PC，2：安卓，3：IOS
	 */
	public java.lang.Byte getReaddevice() {
		return getByte("readdevice");
	}

	/**
	 * 对方阅读消息时，所在的ip，ip_info的id字段
	 */
	public void setReadipid(java.lang.Integer readipid) {
		set("readipid", readipid);
	}
	
	/**
	 * 对方阅读消息时，所在的ip，ip_info的id字段
	 */
	public java.lang.Integer getReadipid() {
		return getInt("readipid");
	}

	/**
	 * 私聊归属uid字符串，'大_小'
	 */
	public void setTwouid(java.lang.String twouid) {
		set("twouid", twouid);
	}
	
	/**
	 * 私聊归属uid字符串，'大_小'
	 */
	public java.lang.String getTwouid() {
		return getStr("twouid");
	}

	/**
	 * 记录创建时间
	 */
	public void setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
	}
	
	/**
	 * 记录创建时间
	 */
	public java.util.Date getCreatetime() {
		return get("createtime");
	}

	/**
	 * 该记录更新时间
	 */
	public void setUpdatetime(java.util.Date updatetime) {
		set("updatetime", updatetime);
	}
	
	/**
	 * 该记录更新时间
	 */
	public java.util.Date getUpdatetime() {
		return get("updatetime");
	}

	/**
	 * 备份时间：一般等于updatetime
	 */
	public void setBaktime(java.util.Date baktime) {
		set("baktime", baktime);
	}
	
	/**
	 * 备份时间：一般等于updatetime
	 */
	public java.util.Date getBaktime() {
		return get("baktime");
	}

}
