/*
 * 使用本软件请从杭州钛特云有限公司获取授权，其它途径获取本软件的行为皆为侵权行为
 * 本源代码由杭州钛特云科技有限公司授权给娄底大新土石方施工有限公司使用
 */
package org.tio.sitexxx.service.model.main.base;

import org.tio.jfinal.plugin.activerecord.IBean;
import org.tio.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUserLevelItem<M extends BaseUserLevelItem<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setUid(java.lang.Integer uid) {
		set("uid", uid);
	}

	public java.lang.Integer getUid() {
		return getInt("uid");
	}

	public void setBusid(java.lang.Integer busid) {
		set("busid", busid);
	}

	public java.lang.Integer getBusid() {
		return getInt("busid");
	}

	public void setType(java.lang.Byte type) {
		set("type", type);
	}

	public java.lang.Byte getType() {
		return getByte("type");
	}

	public void setAddexp(java.lang.Integer addexp) {
		set("addexp", addexp);
	}

	public java.lang.Integer getAddexp() {
		return getInt("addexp");
	}

	public void setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
	}

	public java.util.Date getCreatetime() {
		return get("createtime");
	}

	public void setUpdatetime(java.util.Date updatetime) {
		set("updatetime", updatetime);
	}

	public java.util.Date getUpdatetime() {
		return get("updatetime");
	}

}
