/*
 * 使用本软件请从杭州钛特云有限公司获取授权，其它途径获取本软件的行为皆为侵权行为
 * 本源代码由杭州钛特云科技有限公司授权给娄底大新土石方施工有限公司使用
 */
package org.tio.sitexxx.service.model.main.base;

import org.tio.sitexxx.service.jf.TioModel;
import org.tio.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseWxGroupBak<M extends BaseWxGroupBak<M>> extends TioModel<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	/**
	 * 群名称
	 */
	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	/**
	 * 群名称
	 */
	public java.lang.String getName() {
		return getStr("name");
	}

	/**
	 *  群主的userid
	 */
	public void setUid(java.lang.Integer uid) {
		set("uid", uid);
	}
	
	/**
	 *  群主的userid
	 */
	public java.lang.Integer getUid() {
		return getInt("uid");
	}

	/**
	 * 进群方式：1、群主邀请；2：群主审核；3：直接入群
	 */
	public void setJoinmode(java.lang.Byte joinmode) {
		set("joinmode", joinmode);
	}
	
	/**
	 * 进群方式：1、群主邀请；2：群主审核；3：直接入群
	 */
	public java.lang.Byte getJoinmode() {
		return getByte("joinmode");
	}

	/**
	 * 是否进行消息激活群：1：是；2：否
	 */
	public void setMsgactflag(java.lang.Byte msgactflag) {
		set("msgactflag", msgactflag);
	}
	
	/**
	 * 是否进行消息激活群：1：是；2：否
	 */
	public java.lang.Byte getMsgactflag() {
		return getByte("msgactflag");
	}

	/**
	 * 群头像
	 */
	public void setAvatar(java.lang.String avatar) {
		set("avatar", avatar);
	}
	
	/**
	 * 群头像
	 */
	public java.lang.String getAvatar() {
		return getStr("avatar");
	}

	/**
	 * 群公告
	 */
	public void setNotice(java.lang.String notice) {
		set("notice", notice);
	}
	
	/**
	 * 群公告
	 */
	public java.lang.String getNotice() {
		return getStr("notice");
	}

	/**
	 * 当前群的状态：1、正常；2、被封；3、群主删除
	 */
	public void setStatus(java.lang.Byte status) {
		set("status", status);
	}
	
	/**
	 * 当前群的状态：1、正常；2、被封；3、群主删除
	 */
	public java.lang.Byte getStatus() {
		return getByte("status");
	}

	/**
	 * 群简介
	 */
	public void setIntro(java.lang.String intro) {
		set("intro", intro);
	}
	
	/**
	 * 群简介
	 */
	public java.lang.String getIntro() {
		return getStr("intro");
	}

	/**
	 *  群创建时间
	 */
	public void setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
	}
	
	/**
	 *  群创建时间
	 */
	public java.util.Date getCreatetime() {
		return get("createtime");
	}

	/**
	 *  群资料更新时间
	 */
	public void setUpdatetime(java.util.Date updatetime) {
		set("updatetime", updatetime);
	}
	
	/**
	 *  群资料更新时间
	 */
	public java.util.Date getUpdatetime() {
		return get("updatetime");
	}

	/**
	 * 备份时间：一般等于updatetime
	 */
	public void setBaktime(java.util.Date baktime) {
		set("baktime", baktime);
	}
	
	/**
	 * 备份时间：一般等于updatetime
	 */
	public java.util.Date getBaktime() {
		return get("baktime");
	}

}
