package org.tio.sitexxx.service.model.main.base;

import org.tio.sitexxx.service.jf.TioModel;
import org.tio.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseWxSynItem<M extends BaseWxSynItem<M>> extends TioModel<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 用户id
	 */
	public void setUid(java.lang.Integer uid) {
		set("uid", uid);
	}
	
	/**
	 * 用户id
	 */
	public java.lang.Integer getUid() {
		return getInt("uid");
	}

	/**
	 * 设备类型
	 */
	public void setDevicetype(java.lang.Byte devicetype) {
		set("devicetype", devicetype);
	}
	
	/**
	 * 设备类型
	 */
	public java.lang.Byte getDevicetype() {
		return getByte("devicetype");
	}

	/**
	 * 同步类型：1:会话
	 */
	public void setSyntype(java.lang.Byte syntype) {
		set("syntype", syntype);
	}
	
	/**
	 * 同步类型：1:会话
	 */
	public java.lang.Byte getSyntype() {
		return getByte("syntype");
	}

	/**
	 * 同步时间
	 */
	public void setSyntime(java.util.Date syntime) {
		set("syntime", syntime);
	}
	
	/**
	 * 同步时间
	 */
	public java.util.Date getSyntime() {
		return get("syntime");
	}

	/**
	 * 记录创建时间
	 */
	public void setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
	}
	
	/**
	 * 记录创建时间
	 */
	public java.util.Date getCreatetime() {
		return get("createtime");
	}

	/**
	 * 记录更新时间
	 */
	public void setUpdatetime(java.util.Date updatetime) {
		set("updatetime", updatetime);
	}
	
	/**
	 * 记录更新时间
	 */
	public java.util.Date getUpdatetime() {
		return get("updatetime");
	}

}
