package org.tio.sitexxx.service.model.main.base;

import org.tio.sitexxx.service.jf.TioModel;
import org.tio.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseYxUserWalletItem<M extends BaseYxUserWalletItem<M>> extends TioModel<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 用户id
	 */
	public void setUid(java.lang.Integer uid) {
		set("uid", uid);
	}
	
	/**
	 * 用户id
	 */
	public java.lang.Integer getUid() {
		return getInt("uid");
	}

	/**
	 * 钱包ID
	 */
	public void setWalletid(java.lang.Integer walletid) {
		set("walletid", walletid);
	}
	
	/**
	 * 钱包ID
	 */
	public java.lang.Integer getWalletid() {
		return getInt("walletid");
	}

	public void setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
	}
	
	public java.util.Date getCreatetime() {
		return get("createtime");
	}

	public void setUpdatetime(java.util.Date updatetime) {
		set("updatetime", updatetime);
	}
	
	public java.util.Date getUpdatetime() {
		return get("updatetime");
	}

	/**
	 * 金额
	 */
	public void setAmount(java.lang.Integer amount) {
		set("amount", amount);
	}
	
	/**
	 * 金额
	 */
	public java.lang.Integer getAmount() {
		return getInt("amount");
	}

	/**
	 * 该笔记录通过后余额
	 */
	public void setAmountall(java.lang.Integer amountall) {
		set("amountall", amountall);
	}
	
	/**
	 * 该笔记录通过后余额
	 */
	public java.lang.Integer getAmountall() {
		return getInt("amountall");
	}

	/**
	 * 收支：1：收入；2：支出
	 */
	public void setCoinflag(java.lang.Integer coinflag) {
		set("coinflag", coinflag);
	}
	
	/**
	 * 收支：1：收入；2：支出
	 */
	public java.lang.Integer getCoinflag() {
		return getInt("coinflag");
	}

	/**
	 * 1充值 2提现 3红包 4其他
	 */
	public void setMode(java.lang.Integer mode) {
		set("mode", mode);
	}
	
	/**
	 * 1充值 2提现 3红包 4其他
	 */
	public java.lang.Integer getMode() {
		return getInt("mode");
	}

	/**
	 * 业务编号
	 */
	public void setBizid(java.lang.Integer bizid) {
		set("bizid", bizid);
	}
	
	/**
	 * 业务编号
	 */
	public java.lang.Integer getBizid() {
		return getInt("bizid");
	}

	/**
	 * 业务流水号。红包则为红包业务编号，充值则为充值流水号，提现为提现流水号
	 */
	public void setBiznumber(java.lang.String biznumber) {
		set("biznumber", biznumber);
	}
	
	/**
	 * 业务流水号。红包则为红包业务编号，充值则为充值流水号，提现为提现流水号
	 */
	public java.lang.String getBiznumber() {
		return getStr("biznumber");
	}

	/**
	 * 备注
	 */
	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}
	
	/**
	 * 备注
	 */
	public java.lang.String getRemark() {
		return getStr("remark");
	}

	public void setExt1(java.lang.String ext1) {
		set("ext1", ext1);
	}
	
	public java.lang.String getExt1() {
		return getStr("ext1");
	}

	public void setExt2(java.lang.String ext2) {
		set("ext2", ext2);
	}
	
	public java.lang.String getExt2() {
		return getStr("ext2");
	}

	public void setExt3(java.lang.String ext3) {
		set("ext3", ext3);
	}
	
	public java.lang.String getExt3() {
		return getStr("ext3");
	}

}
