package org.tio.sitexxx.service.model.main.base;

import org.tio.sitexxx.service.jf.TioModel;
import org.tio.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseYxUserWithdraw<M extends BaseYxUserWithdraw<M>> extends TioModel<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 用户id
	 */
	public void setUid(java.lang.Integer uid) {
		set("uid", uid);
	}
	
	/**
	 * 用户id
	 */
	public java.lang.Integer getUid() {
		return getInt("uid");
	}

	/**
	 * 用户昵称
	 */
	public void setUnick(java.lang.String unick) {
		set("unick", unick);
	}
	
	/**
	 * 用户昵称
	 */
	public java.lang.String getUnick() {
		return getStr("unick");
	}

	/**
	 * 用户钱包ID
	 */
	public void setWalletid(java.lang.Integer walletid) {
		set("walletid", walletid);
	}
	
	/**
	 * 用户钱包ID
	 */
	public java.lang.Integer getWalletid() {
		return getInt("walletid");
	}

	public void setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
	}
	
	public java.util.Date getCreatetime() {
		return get("createtime");
	}

	public void setUpdatetime(java.util.Date updatetime) {
		set("updatetime", updatetime);
	}
	
	public java.util.Date getUpdatetime() {
		return get("updatetime");
	}

	/**
	 * 提现时账户余额
	 */
	public void setAmountacount(java.lang.Integer amountacount) {
		set("amountacount", amountacount);
	}
	
	/**
	 * 提现时账户余额
	 */
	public java.lang.Integer getAmountacount() {
		return getInt("amountacount");
	}

	/**
	 * 实际提现到账金额，
	 */
	public void setAmountreal(java.lang.Integer amountreal) {
		set("amountreal", amountreal);
	}
	
	/**
	 * 实际提现到账金额，
	 */
	public java.lang.Integer getAmountreal() {
		return getInt("amountreal");
	}

	/**
	 * 手续费
	 */
	public void setAmountcommission(java.lang.Integer amountcommission) {
		set("amountcommission", amountcommission);
	}
	
	/**
	 * 手续费
	 */
	public java.lang.Integer getAmountcommission() {
		return getInt("amountcommission");
	}

	/**
	 * 实际扣费金额
	 */
	public void setAmountall(java.lang.Integer amountall) {
		set("amountall", amountall);
	}
	
	/**
	 * 实际扣费金额
	 */
	public java.lang.Integer getAmountall() {
		return getInt("amountall");
	}

	/**
	 * 提现账号ID
	 */
	public void setWithdrawacountid(java.lang.Integer withdrawacountid) {
		set("withdrawacountid", withdrawacountid);
	}
	
	/**
	 * 提现账号ID
	 */
	public java.lang.Integer getWithdrawacountid() {
		return getInt("withdrawacountid");
	}

	/**
	 * 流水号
	 */
	public void setSerial(java.lang.String serial) {
		set("serial", serial);
	}
	
	/**
	 * 流水号
	 */
	public java.lang.String getSerial() {
		return getStr("serial");
	}

	/**
	 * 提现申请时备注
	 */
	public void setWithdrawremark(java.lang.String withdrawremark) {
		set("withdrawremark", withdrawremark);
	}
	
	/**
	 * 提现申请时备注
	 */
	public java.lang.String getWithdrawremark() {
		return getStr("withdrawremark");
	}

	/**
	 * 提现状态：1待审核 2审核中 3已通过 4拒绝5提现完成
	 */
	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}
	
	/**
	 * 提现状态：1待审核 2审核中 3已通过 4拒绝5提现完成
	 */
	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	/**
	 * 审核人ID
	 */
	public void setReviewuid(java.lang.Integer reviewuid) {
		set("reviewuid", reviewuid);
	}
	
	/**
	 * 审核人ID
	 */
	public java.lang.Integer getReviewuid() {
		return getInt("reviewuid");
	}

	/**
	 * 审核时间完成时间
	 */
	public void setReviewtime(java.util.Date reviewtime) {
		set("reviewtime", reviewtime);
	}
	
	/**
	 * 审核时间完成时间
	 */
	public java.util.Date getReviewtime() {
		return get("reviewtime");
	}

	/**
	 * 审核意见
	 */
	public void setReviewremark(java.lang.String reviewremark) {
		set("reviewremark", reviewremark);
	}
	
	/**
	 * 审核意见
	 */
	public java.lang.String getReviewremark() {
		return getStr("reviewremark");
	}

	public void setExt1(java.lang.String ext1) {
		set("ext1", ext1);
	}
	
	public java.lang.String getExt1() {
		return getStr("ext1");
	}

	public void setExt2(java.lang.String ext2) {
		set("ext2", ext2);
	}
	
	public java.lang.String getExt2() {
		return getStr("ext2");
	}

	public void setExt3(java.lang.String ext3) {
		set("ext3", ext3);
	}
	
	public java.lang.String getExt3() {
		return getStr("ext3");
	}

}
