package org.tio.mg.service.model.conf.base;

import org.tio.mg.service.jf.TioModel;
import org.tio.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseWebsite<M extends BaseWebsite<M>> extends TioModel<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 创建时间
	 */
	public void setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreatetime() {
		return get("createtime");
	}

	/**
	 * 修改时间
	 */
	public void setUpdatetime(java.util.Date updatetime) {
		set("updatetime", updatetime);
	}
	
	/**
	 * 修改时间
	 */
	public java.util.Date getUpdatetime() {
		return get("updatetime");
	}

	public void setSitename(java.lang.String sitename) {
		set("sitename", sitename);
	}
	
	public java.lang.String getSitename() {
		return getStr("sitename");
	}

	public void setSiteurl(java.lang.String siteurl) {
		set("siteurl", siteurl);
	}
	
	public java.lang.String getSiteurl() {
		return getStr("siteurl");
	}

	public void setSiteicon(java.lang.String siteicon) {
		set("siteicon", siteicon);
	}
	
	public java.lang.String getSiteicon() {
		return getStr("siteicon");
	}

}
