package org.tio.mg.service.model.conf.base;

import org.tio.mg.service.jf.TioModel;
import org.tio.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseYxConf<M extends BaseYxConf<M>> extends TioModel<M> implements IBean {

	/**
	 * 主键
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	/**
	 * 主键
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 参数说明
	 */
	public void setTitle(java.lang.String title) {
		set("title", title);
	}
	
	/**
	 * 参数说明
	 */
	public java.lang.String getTitle() {
		return getStr("title");
	}

	/**
	 * 参数名称
	 */
	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	/**
	 * 参数名称
	 */
	public java.lang.String getName() {
		return getStr("name");
	}

	/**
	 * 参数值
	 */
	public void setValue(java.lang.String value) {
		set("value", value);
	}
	
	/**
	 * 参数值
	 */
	public java.lang.String getValue() {
		return getStr("value");
	}

	/**
	 * 配置备注
	 */
	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}
	
	/**
	 * 配置备注
	 */
	public java.lang.String getRemark() {
		return getStr("remark");
	}

	/**
	 * 单位
	 */
	public void setUnit(java.lang.String unit) {
		set("unit", unit);
	}
	
	/**
	 * 单位
	 */
	public java.lang.String getUnit() {
		return getStr("unit");
	}

	/**
	 * 1：客户端配置；2：服务端配置；3：支付配置 4：接口配置
	 */
	public void setConftype(java.lang.Byte conftype) {
		set("conftype", conftype);
	}
	
	/**
	 * 1：客户端配置；2：服务端配置；3：支付配置 4：接口配置
	 */
	public java.lang.Byte getConftype() {
		return getByte("conftype");
	}

	/**
	 * 类型：1：文本；2：下拉框
	 */
	public void setType(java.lang.Byte type) {
		set("type", type);
	}
	
	/**
	 * 类型：1：文本；2：下拉框
	 */
	public java.lang.Byte getType() {
		return getByte("type");
	}

	/**
	 * 0-需要下发给客户端
	 */
	public void setClientConf(java.lang.Byte clientConf) {
		set("client_conf", clientConf);
	}
	
	/**
	 * 0-需要下发给客户端
	 */
	public java.lang.Byte getClientConf() {
		return getByte("client_conf");
	}

	/**
	 * 该条记录更新时间
	 */
	public void setUpdatetime(java.util.Date updatetime) {
		set("updatetime", updatetime);
	}
	
	/**
	 * 该条记录更新时间
	 */
	public java.util.Date getUpdatetime() {
		return get("updatetime");
	}

	/**
	 * 创建时间
	 */
	public void setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreatetime() {
		return get("createtime");
	}

	public void setSort(java.lang.Integer sort) {
		set("sort", sort);
	}
	
	public java.lang.Integer getSort() {
		return getInt("sort");
	}

}
