package org.tio.sitexxx.service.model.conf;

import org.tio.sitexxx.service.model.conf.base.BaseAnnouncement;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Announcement extends BaseAnnouncement<Announcement> {
	public static final Announcement dao = new Announcement().dao();
}
