/*
 * 使用本软件请从杭州钛特云有限公司获取授权，其它途径获取本软件的行为皆为侵权行为
 * 本源代码由杭州钛特云科技有限公司授权给娄底大新土石方施工有限公司使用
 */
package org.tio.sitexxx.service.model.conf;

import java.util.List;

import org.tio.sitexxx.service.model.conf.base.BaseArea;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Area extends BaseArea<Area> {
	public static final Area dao = new Area().dao();

	private List<Area> childArea;

	private Area parentArea;

	public List<Area> getChildArea() {
		return childArea;
	}

	public void setChildArea(List<Area> childArea) {
		this.childArea = childArea;
	}

	public Area getParentArea() {
		return parentArea;
	}

	public void setParentArea(Area parentArea) {
		this.parentArea = parentArea;
	}

}
