/*
 * 使用本软件请从杭州钛特云有限公司获取授权，其它途径获取本软件的行为皆为侵权行为
 * 本源代码由杭州钛特云科技有限公司授权给娄底大新土石方施工有限公司使用
 */
package org.tio.sitexxx.service.model.conf;

import org.tio.sitexxx.service.model.conf.base.BaseIpBlackList;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class IpBlackList extends BaseIpBlackList<IpBlackList> {
	public static final IpBlackList dao = new IpBlackList().dao();
}
