package org.tio.sitexxx.service.model.conf;

import org.tio.sitexxx.service.model.conf.base.BaseWebsite;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Website extends BaseWebsite<Website> {
	public static final Website dao = new Website().dao();
}
