package org.tio.sitexxx.service.model.conf.base;

import org.tio.sitexxx.service.jf.TioModel;
import org.tio.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSensitiveWordsList<M extends BaseSensitiveWordsList<M>> extends TioModel<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 敏感词
	 */
	public void setWord(java.lang.String word) {
		set("word", word);
	}
	
	/**
	 * 敏感词
	 */
	public java.lang.String getWord() {
		return getStr("word");
	}

	/**
	 * 1有效；0无效
	 */
	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}
	
	/**
	 * 1有效；0无效
	 */
	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	/**
	 * 最后一个操作的人
	 */
	public void setMguid(java.lang.Integer mguid) {
		set("mguid", mguid);
	}
	
	/**
	 * 最后一个操作的人
	 */
	public java.lang.Integer getMguid() {
		return getInt("mguid");
	}

	/**
	 * 创建时间
	 */
	public void setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreatetime() {
		return get("createtime");
	}

	/**
	 * 修改时间
	 */
	public void setUpdatetime(java.util.Date updatetime) {
		set("updatetime", updatetime);
	}
	
	/**
	 * 修改时间
	 */
	public java.util.Date getUpdatetime() {
		return get("updatetime");
	}

}
