package org.tio.sitexxx.service.model.conf.base;

import org.tio.sitexxx.service.jf.TioModel;
import org.tio.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAnnouncement<M extends BaseAnnouncement<M>> extends TioModel<M> implements IBean {

	/**
	 * id主键
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	/**
	 * id主键
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 公告标题
	 */
	public void setTitle(java.lang.String title) {
		set("title", title);
	}
	
	/**
	 * 公告标题
	 */
	public java.lang.String getTitle() {
		return getStr("title");
	}

	/**
	 * 公告作者
	 */
	public void setAuthor(java.lang.String author) {
		set("author", author);
	}
	
	/**
	 * 公告作者
	 */
	public java.lang.String getAuthor() {
		return getStr("author");
	}

	/**
	 * 纯粹的富文本内容
	 */
	public void setBody(java.lang.String body) {
		set("body", body);
	}
	
	/**
	 * 纯粹的富文本内容
	 */
	public java.lang.String getBody() {
		return getStr("body");
	}

	/**
	 * 公告通知的完整富文本内容（包含 html 头 ，内容，和尾部），用来给app显示用
	 */
	public void setContent(java.lang.String content) {
		set("content", content);
	}
	
	/**
	 * 公告通知的完整富文本内容（包含 html 头 ，内容，和尾部），用来给app显示用
	 */
	public java.lang.String getContent() {
		return getStr("content");
	}

	/**
	 * 状态（1.待发布2正在显示3.已发布）
	 */
	public void setStatus(java.lang.Byte status) {
		set("status", status);
	}
	
	/**
	 * 状态（1.待发布2正在显示3.已发布）
	 */
	public java.lang.Byte getStatus() {
		return getByte("status");
	}

	/**
	 * 发布时间
	 */
	public void setPublishtime(java.util.Date publishtime) {
		set("publishtime", publishtime);
	}
	
	/**
	 * 发布时间
	 */
	public java.util.Date getPublishtime() {
		return get("publishtime");
	}

	/**
	 * 停用时间
	 */
	public void setStoptime(java.util.Date stoptime) {
		set("stoptime", stoptime);
	}
	
	/**
	 * 停用时间
	 */
	public java.util.Date getStoptime() {
		return get("stoptime");
	}

	/**
	 * 后台操作人的uid
	 */
	public void setOperatorId(java.lang.Integer operatorId) {
		set("operator_id", operatorId);
	}
	
	/**
	 * 后台操作人的uid
	 */
	public java.lang.Integer getOperatorId() {
		return getInt("operator_id");
	}

	/**
	 * 用来校对当前记录的md5
	 */
	public void setMd5(java.lang.String md5) {
		set("md5", md5);
	}
	
	/**
	 * 用来校对当前记录的md5
	 */
	public java.lang.String getMd5() {
		return getStr("md5");
	}

	/**
	 * 创建记录的时间
	 */
	public void setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
	}
	
	/**
	 * 创建记录的时间
	 */
	public java.util.Date getCreatetime() {
		return get("createtime");
	}

	/**
	 * 更新数据的时间
	 */
	public void setUpdatetime(java.util.Date updatetime) {
		set("updatetime", updatetime);
	}
	
	/**
	 * 更新数据的时间
	 */
	public java.util.Date getUpdatetime() {
		return get("updatetime");
	}

}
