/*
 * 使用本软件请从杭州钛特云有限公司获取授权，其它途径获取本软件的行为皆为侵权行为
 * 本源代码由杭州钛特云科技有限公司授权给娄底大新土石方施工有限公司使用
 */package org.tio.mg.service.model.stat.base;

import org.tio.mg.service.jf.TioModel;
import org.tio.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAdStat<M extends BaseAdStat<M>> extends TioModel<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * ts_ad表的id
	 */
	public void setAdId(java.lang.Integer adId) {
		set("ad_id", adId);
	}
	
	/**
	 * ts_ad表的id
	 */
	public java.lang.Integer getAdId() {
		return getInt("ad_id");
	}

	public void setAdUrl(java.lang.String adUrl) {
		set("ad_url", adUrl);
	}
	
	public java.lang.String getAdUrl() {
		return getStr("ad_url");
	}

	public void setReferer(java.lang.String referer) {
		set("referer", referer);
	}
	
	public java.lang.String getReferer() {
		return getStr("referer");
	}

	public void setUserAgent(java.lang.String userAgent) {
		set("user_agent", userAgent);
	}
	
	public java.lang.String getUserAgent() {
		return getStr("user_agent");
	}

	public void setIp(java.lang.String ip) {
		set("ip", ip);
	}
	
	public java.lang.String getIp() {
		return getStr("ip");
	}

	public void setIpid(java.lang.Integer ipid) {
		set("ipid", ipid);
	}
	
	public java.lang.Integer getIpid() {
		return getInt("ipid");
	}

	public void setTime(java.util.Date time) {
		set("time", time);
	}
	
	public java.util.Date getTime() {
		return get("time");
	}

	/**
	 * 1、点击跳转，2：内嵌显示
	 */
	public void setType(java.lang.Byte type) {
		set("type", type);
	}
	
	/**
	 * 1、点击跳转，2：内嵌显示
	 */
	public java.lang.Byte getType() {
		return getByte("type");
	}

	/**
	 * 用户的sessionid
	 */
	public void setSessionid(java.lang.String sessionid) {
		set("sessionid", sessionid);
	}
	
	/**
	 * 用户的sessionid
	 */
	public java.lang.String getSessionid() {
		return getStr("sessionid");
	}

	public void setUid(java.lang.Integer uid) {
		set("uid", uid);
	}
	
	public java.lang.Integer getUid() {
		return getInt("uid");
	}

}
