package org.tio.mg.service.model.conf;

import org.tio.mg.service.model.conf.base.BaseBankConf;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BankConf extends BaseBankConf<BankConf> {
	public static final BankConf dao = new BankConf().dao();
}
