package org.tio.mg.service.model.conf;

import org.tio.mg.service.model.conf.base.BaseSensitiveWordsList;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SensitiveWordsList extends BaseSensitiveWordsList<SensitiveWordsList> {
	public static final SensitiveWordsList dao = new SensitiveWordsList().dao();
}
