package org.tio.mg.service.model.conf;

import org.tio.mg.service.model.conf.base.BaseYxConf;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class YxConf extends BaseYxConf<YxConf> {
	public static final YxConf dao = new YxConf().dao();
}
