package org.tio.mg.service.model.mg.base;

import org.tio.mg.service.jf.TioModel;
import org.tio.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMgRoleMenu<M extends BaseMgRoleMenu<M>> extends TioModel<M> implements IBean {

	/**
	 * id
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	/**
	 * id
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 角色id
	 */
	public void setRoleId(java.lang.Integer roleId) {
		set("role_id", roleId);
	}
	
	/**
	 * 角色id
	 */
	public java.lang.Integer getRoleId() {
		return getInt("role_id");
	}

	/**
	 * 菜单id
	 */
	public void setMenuId(java.lang.Integer menuId) {
		set("menu_id", menuId);
	}
	
	/**
	 * 菜单id
	 */
	public java.lang.Integer getMenuId() {
		return getInt("menu_id");
	}

	/**
	 * 添加时间
	 */
	public void setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
	}
	
	/**
	 * 添加时间
	 */
	public java.util.Date getCreatetime() {
		return get("createtime");
	}

}
