package org.tio.mg.service.model.mg.base;

import org.tio.mg.service.jf.TioModel;
import org.tio.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMgOperRecord<M extends BaseMgOperRecord<M>> extends TioModel<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 创建时间
	 */
	public void setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreatetime() {
		return get("createtime");
	}

	/**
	 * 修改时间
	 */
	public void setUpdatetime(java.util.Date updatetime) {
		set("updatetime", updatetime);
	}
	
	/**
	 * 修改时间
	 */
	public java.util.Date getUpdatetime() {
		return get("updatetime");
	}

	/**
	 * 操作者UID
	 */
	public void setUid(java.lang.Integer uid) {
		set("uid", uid);
	}
	
	/**
	 * 操作者UID
	 */
	public java.lang.Integer getUid() {
		return getInt("uid");
	}

	/**
	 * 操作者名称
	 */
	public void setUsername(java.lang.String username) {
		set("username", username);
	}
	
	/**
	 * 操作者名称
	 */
	public java.lang.String getUsername() {
		return getStr("username");
	}

	/**
	 * 操作类型 1:新增；2：修改；3：删除；4：禁用；5：重置
	 */
	public void setOpertype(java.lang.Byte opertype) {
		set("opertype", opertype);
	}
	
	/**
	 * 操作类型 1:新增；2：修改；3：删除；4：禁用；5：重置
	 */
	public java.lang.Byte getOpertype() {
		return getByte("opertype");
	}

	/**
	 * 操作ip
	 */
	public void setOperip(java.lang.String operip) {
		set("operip", operip);
	}
	
	/**
	 * 操作ip
	 */
	public java.lang.String getOperip() {
		return getStr("operip");
	}

	/**
	 * 操作参数
	 */
	public void setOperparam(java.lang.String operparam) {
		set("operparam", operparam);
	}
	
	/**
	 * 操作参数
	 */
	public java.lang.String getOperparam() {
		return getStr("operparam");
	}

	/**
	 * 设备信息
	 */
	public void setDeviceinfo(java.lang.String deviceinfo) {
		set("deviceinfo", deviceinfo);
	}
	
	/**
	 * 设备信息
	 */
	public java.lang.String getDeviceinfo() {
		return getStr("deviceinfo");
	}

	/**
	 * 模块名称
	 */
	public void setModename(java.lang.String modename) {
		set("modename", modename);
	}
	
	/**
	 * 模块名称
	 */
	public java.lang.String getModename() {
		return getStr("modename");
	}

	public void setContent(java.lang.String content) {
		set("content", content);
	}
	
	public java.lang.String getContent() {
		return getStr("content");
	}

}
