package org.tio.mg.service.model.mg.base;

import org.tio.mg.service.jf.TioModel;
import org.tio.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMgMenu<M extends BaseMgMenu<M>> extends TioModel<M> implements IBean {

	/**
	 * 菜单id
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	/**
	 * 菜单id
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 父节点的id
	 */
	public void setParentId(java.lang.Integer parentId) {
		set("parent_id", parentId);
	}
	
	/**
	 * 父节点的id
	 */
	public java.lang.Integer getParentId() {
		return getInt("parent_id");
	}

	/**
	 * 路由路径
	 */
	public void setPath(java.lang.String path) {
		set("path", path);
	}
	
	/**
	 * 路由路径
	 */
	public java.lang.String getPath() {
		return getStr("path");
	}

	/**
	 * 菜单名称英文
	 */
	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	/**
	 * 菜单名称英文
	 */
	public java.lang.String getName() {
		return getStr("name");
	}

	/**
	 * 类型（1.菜单2.页面3.操作）
	 */
	public void setType(java.lang.Byte type) {
		set("type", type);
	}
	
	/**
	 * 类型（1.菜单2.页面3.操作）
	 */
	public java.lang.Byte getType() {
		return getByte("type");
	}

	/**
	 * 菜单状态（1.正常2.禁用 ）
	 */
	public void setStatus(java.lang.Byte status) {
		set("status", status);
	}
	
	/**
	 * 菜单状态（1.正常2.禁用 ）
	 */
	public java.lang.Byte getStatus() {
		return getByte("status");
	}

	/**
	 * 菜单名称中文
	 */
	public void setTitle(java.lang.String title) {
		set("title", title);
	}
	
	/**
	 * 菜单名称中文
	 */
	public java.lang.String getTitle() {
		return getStr("title");
	}

	/**
	 * 菜单图标
	 */
	public void setIcon(java.lang.String icon) {
		set("icon", icon);
	}
	
	/**
	 * 菜单图标
	 */
	public java.lang.String getIcon() {
		return getStr("icon");
	}

	/**
	 * 菜单顺序
	 */
	public void setSort(java.lang.Byte sort) {
		set("sort", sort);
	}
	
	/**
	 * 菜单顺序
	 */
	public java.lang.Byte getSort() {
		return getByte("sort");
	}

	/**
	 * 创建时间
	 */
	public void setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreatetime() {
		return get("createtime");
	}

	/**
	 * 更新时间
	 */
	public void setUpdatetime(java.util.Date updatetime) {
		set("updatetime", updatetime);
	}
	
	/**
	 * 更新时间
	 */
	public java.util.Date getUpdatetime() {
		return get("updatetime");
	}

}
