/*
 * 使用本软件请从杭州钛特云有限公司获取授权，其它途径获取本软件的行为皆为侵权行为
 * 本源代码由杭州钛特云科技有限公司授权给娄底大新土石方施工有限公司使用
 */package org.tio.mg.service.model.stat;

import org.tio.mg.service.model.stat.base.BaseUserRegisterStat;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserRegisterStat extends BaseUserRegisterStat<UserRegisterStat> {
	public static final UserRegisterStat dao = new UserRegisterStat().dao();
	/**
	 * 统计维度
	 * @author xufei
	 * 2020年7月13日 下午2:43:13
	 */
	public static interface Type {
		/**
		 * 时间
		 */
		byte TIME = 1;

		/**
		 * ip
		 */
		byte IP = 2;
		
		/**
		 * ip下的时间维度
		 */
		byte IP_TIME = 3;
	}
}
