/*
 * 使用本软件请从杭州钛特云有限公司获取授权，其它途径获取本软件的行为皆为侵权行为
 * 本源代码由杭州钛特云科技有限公司授权给娄底大新土石方施工有限公司使用
 */
package org.tio.mg.service.model.main;

import org.tio.mg.service.model.main.base.BaseRechargeItem;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RechargeItem extends BaseRechargeItem<RechargeItem> {
	public static final RechargeItem dao = new RechargeItem().dao();

	public Double getAddcoin() {
		return getDouble("addcoin");
	}

	public void setAddcoin(Double addcoin) {
		put("addcoin", addcoin);
	}

	public void setCreatetime(java.util.Date createtime) {
		put("createtime", createtime);
	}

	public java.util.Date getCreatetime() {
		return get("createtime");
	}

	/**
	 * 充值附属业务
	 * 
	 * @date 2016年10月18日 下午3:22:01
	 */
	public static interface BizType {

	}

	/**
	 * 支付类型
	 * @author tanyaowu
	 *
	 */
	public static interface Paytype {
		/**
		 * 支付宝--WS
		 */
		Integer	ALIPAY		= 1;
		/**
		 * 支付宝--APP版
		 */
		Integer	ALIPAY_APP	= 11;

		/**
		 * 支付宝--H5版
		 */
		Integer ALIPAY_H5 = 111;

		/**
		 * 微信--PC扫码
		 */
		Integer WEIXIN = 2;

		/**
		 * 微信--APP
		 */
		Integer WEIXIN_APP = 22;

		/**
		 * 微信--H5
		 */
		Integer WEIXIN_H5 = 222;

		/**
		 * 微信--JSAPI（公众号）
		 */
		Integer WEIXIN_JSAPI = 2222;

		/**
		 * 苹果支持（内购）
		 */
		Integer APPLE_APP = 33;

	}

	//	private String userAccountLogNo;

	/**
	 * 订单状态
	 * @author tanyaowu
	 *
	 */
	public static interface Status {
		/**
		 * 未付款
		 */
		public static final int	NO_PAY		= 1;
		/**
		 * 付款成功
		 */
		public static final int	SUCCESS		= 2;
		/**
		 * 取消或关闭
		 */
		public static final int	CANCELED	= 3;
		/**
		 * 已经完成（此状态后，不可退款）
		 */
		public static final int	FINISHED	= 4;

		/**
		 * 受到攻击
		 */
		public static final int ATTACK = 9;

		/**
		 * 其它（正常逻辑不会走到这）
		 */
		public static final int OTHER = 99;
	}

	/**
	 * @param args
	 */
	public static void main(String[] args) {

	}
}
