package org.tio.mg.service.model.main;

import org.tio.mg.service.model.main.base.BaseUserInvite;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserInvite extends BaseUserInvite<UserInvite> {
	public static final UserInvite dao = new UserInvite().dao();
}
