/*
 * 使用本软件请从杭州钛特云有限公司获取授权，其它途径获取本软件的行为皆为侵权行为
 * 本源代码由杭州钛特云科技有限公司授权给娄底大新土石方施工有限公司使用
 */
package org.tio.mg.service.model.main;

import org.tio.mg.service.model.main.base.BaseUserCoin;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserCoin extends BaseUserCoin<UserCoin> {
	public static final UserCoin dao = new UserCoin().dao();

	public void setLevel(java.lang.Integer level) {
		put("level", level);
	}

	public java.lang.Integer getLevel() {
		return getInt("level");
	}

	public String getNick() {
		return get("nick");
	}

	public void setNick(String nick) {
		put("nick", nick);
	}

	public String getAvatar() {
		return get("avatar");
	}

	public void setAvatar(String avatar) {
		put("avatar", avatar);
	}

	public void setExp(java.lang.Double exp) {
		put("exp", exp);
	}

	public java.lang.Double getExp() {
		return getDouble("exp");
	}

	public void setEndexp(java.lang.Double endexp) {
		put("endexp", endexp);
	}

	public java.lang.Double getEndexp() {
		return getDouble("endexp");
	}

	public void setStartexp(java.lang.Double startexp) {
		put("startexp", startexp);
	}

	public java.lang.Double getStartexp() {
		return getDouble("startexp");
	}

	public void setLevelRate(Float levelRate) {
		put("levelRate", levelRate);
	}

	public Float getLevelRate() {
		return getFloat("levelRate");
	}

	public void setDifexp(java.lang.Double difexp) {
		put("difexp", difexp);
	}

	public java.lang.Double getDifexp() {
		return getDouble("difexp");
	}

}
