package org.tio.mg.service.model.main;

import org.tio.mg.service.model.main.base.BaseUserExt;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserExt extends BaseUserExt<UserExt> {
	public static final UserExt dao = new UserExt().dao();
}
