/*
 * 使用本软件请从杭州钛特云有限公司获取授权，其它途径获取本软件的行为皆为侵权行为
 * 本源代码由杭州钛特云科技有限公司授权给娄底大新土石方施工有限公司使用
 */
package org.tio.mg.service.model.main;

import java.util.List;

import org.tio.mg.service.model.main.base.BaseUser;

/**
 * Generated by JFinal.
 */
public class User extends BaseUser<User> {
	public static final User dao = new User().dao();

	/**
	 * 1：正常，5：封停，6：注销
	 *
	 */
	public static interface Status {
		/**
		 * 正常
		 */
		byte NORMAL = 1;

		/**
		 * 封停
		 */
		byte INBLACK = 5;

		/**注销
		 */
		byte LOGOUT = 6;
	}

	/**
	 * 用户id
	 */
	private String uid;

	private List<Byte> roles;

	/**
	 * 是否是后台管理角色
	 */
	private boolean isMg = false;

	private IpInfo ipInfo;

	private String smscode;

	private String checkToken;

	private String smsCheckType;

	private Byte operator;

	private UserThird userThird = null;

	private String captcha;

	private boolean invFlag = false;

	/**
	 * 注册时用于密码确认
	 */
	private String pwd2 = null;

	/**
	 * 您必须 [同意用户服务条款] 才能注册
	 */
	private String agreement = null;

	/**
	 * 默认头像
	 */
	public static final String DEFAULT_AVATAR = "/img/tio.jpg";

	public static interface PwdOperator {
		/**
		 * 找回
		 */
		byte	BACK	= 1;
		/**
		 * 修改
		 */
		byte	UPDATE	= 2;
	}

	private static final long serialVersionUID = 8532842956108994663L;

	public String getUid() {
		return uid;
	}

	public void setUid(String uid) {
		this.uid = uid;
	}

	public List<Byte> getRoles() {
		return roles;
	}

	public void setRoles(List<Byte> roles) {
		this.roles = roles;
	}

	public String getSmscode() {
		return smscode;
	}

	public void setSmscode(String smscode) {
		this.smscode = smscode;
	}

	public String getSmsCheckType() {
		return smsCheckType;
	}

	public void setSmsCheckType(String smsCheckType) {
		this.smsCheckType = smsCheckType;
	}

	public String getCheckToken() {
		return checkToken;
	}

	public void setCheckToken(String checkToken) {
		this.checkToken = checkToken;
	}

	public Byte getOperator() {
		return operator;
	}

	public void setOperator(Byte operator) {
		this.operator = operator;
	}

	public IpInfo getIpInfo() {
		return ipInfo;
	}

	public void setIpInfo(IpInfo ipInfo) {
		this.ipInfo = ipInfo;
	}

	public UserThird getUserThird() {
		return userThird;
	}

	public void setUserThird(UserThird userThird) {
		this.userThird = userThird;
	}

	public String getCaptcha() {
		return captcha;
	}

	public void setCaptcha(String captcha) {
		this.captcha = captcha;
	}

	public boolean isInvFlag() {
		return invFlag;
	}

	public void setInvFlag(boolean invFlag) {
		this.invFlag = invFlag;
	}

	public String getPwd2() {
		return pwd2;
	}

	public void setPwd2(String pwd2) {
		this.pwd2 = pwd2;
	}

	public String getAgreement() {
		return agreement;
	}

	public void setAgreement(String agreement) {
		this.agreement = agreement;
	}

	public boolean isMg() {
		return isMg;
	}

	public void setMg(boolean isMg) {
		this.isMg = isMg;
	}

	public void setSign(java.lang.String sign) {
		put("sign", sign);
	}

	public java.lang.String getSign() {
		return getStr("sign");
	}

	/**
	 * 绑定手机
	 */
	public void setPhone(java.lang.String phone) {
		put("phone", phone);
	}

	/**
	 * 绑定手机
	 */
	public java.lang.String getPhone() {
		return getStr("phone");
	}


	/**
	 * 性别：1：男；2：女
	 */
	public void setSex(java.lang.Byte sex) {
		put("sex", sex);
	}

	/**
	 * 性别：1：男；2：女
	 */
	public java.lang.Byte getSex() {
		return getByte("sex");
	}

	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("【");
		builder.append(getId());
		builder.append("-");
		builder.append(getLoginname());
		builder.append("-");
		builder.append(getNick());
		builder.append("】");
		return builder.toString();
	}
}
