/*
 * 使用本软件请从杭州钛特云有限公司获取授权，其它途径获取本软件的行为皆为侵权行为
 * 本源代码由杭州钛特云科技有限公司授权给娄底大新土石方施工有限公司使用
 */
package org.tio.mg.service.model.main;

import org.tio.mg.service.model.main.base.BaseWxCallItem;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WxCallItem extends BaseWxCallItem<WxCallItem> {
	public static final WxCallItem dao = new WxCallItem().dao();

	/**
	 * 通话类型，是音频通话还是视频通话
	 * @author tanyaowu 
	 * 2020年1月23日 上午10:53:20
	 */
	public static interface CallType {
		/**
		 * 音频通话
		 */
		byte	AUDIO	= 1;
		/**
		 * 视频通话
		 */
		byte	VIDEO	= 2;
	}

	/**
	 * 呼叫状态：1、发起呼叫， 2、信令接通，3、流媒体接通，4、通话结束（拒接、占线、挂断都属于通话结束）
	 * @author tanyaowu 
	 * 2020年2月21日 下午5:42:34
	 */
	public static interface Status {
		/**
		 * 发起呼叫
		 */
		byte	BEGIN_CALLING		= 1;
		/**
		 * 信令接通
		 */
		byte	TCP_CONNECTED		= 2;
		/**
		 * 流媒体接通
		 */
		byte	STREAM_CONNECTED	= 3;
		/**
		 * 通话结束（拒接、占线、挂断都属于通话结束）
		 */
		byte	END					= 4;
	}

	/**
	 * 挂断类型 <br>
	 * 1、正常挂断<br>
	 * 2、拒接挂断<br>
	 * 3、对方正在通话<br>
	 * 4、TCP断开时，系统自动挂断<br>
	 * 5、客户端出现异常，系统自动挂机（譬如获取摄像头失败等），这个请求是客户端发起的挂断请求<br>
	 * 6、ICE服务器异常，这个请求是客户端发起的挂断请求<br>
	 * 7、系统重启<br>
	 * 8、对方不在线<br>
	 * 9、等待响应超时<br>
	 * 10、发起方取消了通话
	 * 99、还没有挂断<br>
	 * @author tanyaowu 
	 * 2020年2月21日 下午6:28:14
	 */
	public static interface Hanguptype {
		/**
		 * 正常挂断
		 */
		byte	NORMAL				= 1;
		/**
		 * 拒接挂断
		 */
		byte	REJECT				= 2;
		/**
		 * 对方正在通话
		 */
		byte	OTHER_SIDE_CALLING	= 3;
		/**
		 * TCP断开时，系统自动挂断
		 */
		byte	TCP_DROPPED			= 4;
		/**
		 * 客户端出现异常，系统自动挂机（譬如获取摄像头失败等），这个请求是客户端发起的挂断请求
		 */
		byte	CLIENT_ERROR		= 5;
		/**
		 * ICE服务器异常，这个请求是客户端发起的挂断请求
		 */
		byte	ICE_ERROR			= 6;
		/**
		 * 系统重启
		 */
		byte	SYSTEM_RESTART		= 7;
		/**
		 * 对方不在线
		 */
		byte	OFFLINE				= 8;
		/**
		 * 等待响应超时
		 */
		byte	RESP_TIMEOUT		= 9;
		/**
		 * 发起方取消了通话
		 */
		byte	CANCELED			= 10;
		/**
		 * 还没有挂断
		 */
		byte	NOT_HANGUP			= 99;
	}

}
