package org.tio.mg.service.model.main;

import org.tio.mg.service.model.main.base.BaseWxFriendGroup;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WxFriendGroup extends BaseWxFriendGroup<WxFriendGroup> {
	public static final WxFriendGroup dao = new WxFriendGroup().dao();
}
