/*
 * 使用本软件请从杭州钛特云有限公司获取授权，其它途径获取本软件的行为皆为侵权行为
 * 本源代码由杭州钛特云科技有限公司授权给娄底大新土石方施工有限公司使用
 */
package org.tio.mg.service.model.main;

import org.tio.mg.service.model.main.base.BaseWxFriendApplyLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WxFriendApplyLog extends BaseWxFriendApplyLog<WxFriendApplyLog> {
	public static final WxFriendApplyLog dao = new WxFriendApplyLog().dao();
	
	private String sessionid;
	
	private String ip;

	public String getSessionid() {
		return sessionid;
	}

	public void setSessionid(String sessionid) {
		this.sessionid = sessionid;
	}

	public String getIp() {
		return ip;
	}

	public void setIp(String ip) {
		this.ip = ip;
	}
}
