/*
 * 使用本软件请从杭州钛特云有限公司获取授权，其它途径获取本软件的行为皆为侵权行为
 * 本源代码由杭州钛特云科技有限公司授权给娄底大新土石方施工有限公司使用
 */
package org.tio.mg.service.model.main;

import org.tio.mg.service.model.main.base.BaseWxFriendApplyItems;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WxFriendApplyItems extends BaseWxFriendApplyItems<WxFriendApplyItems> {
	public static final WxFriendApplyItems dao = new WxFriendApplyItems().dao();
	
	/**
	 * 申请状态
	 * @author xufei
	 * 2020年1月9日 下午2:50:54
	 */
	public static interface ApplyStatus {
		/**
		 *  通过
		 */
		byte PASS = 1;

		/**
		 * 申请中
		 */
		byte APPLY = 2;
		
		/**
		 * 无效：过期/拒绝
		 */
		byte INVALID = 3;
	}
}
