/*
 * 使用本软件请从杭州钛特云有限公司获取授权，其它途径获取本软件的行为皆为侵权行为
 * 本源代码由杭州钛特云科技有限公司授权给娄底大新土石方施工有限公司使用
 */
package org.tio.mg.service.model.main;

import org.tio.mg.service.model.main.base.BaseWxGroup;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WxGroup extends BaseWxGroup<WxGroup> {
	public static final WxGroup dao = new WxGroup().dao();
	public static final String DEFAULT_GROUP_AVATAR = "/img/group.png";
	
	/**
	 * 群人数
	 */
	public void setJoinnum(java.lang.Short joinnum) {
		put("joinnum", joinnum);
	}
	
	/**
	 * 群人数
	 */
	public java.lang.Short getJoinnum() {
		return getShort("joinnum");
	}
}
