package org.tio.mg.service.model.main;

import org.tio.mg.service.model.main.base.BaseWxGroupApply;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WxGroupApply extends BaseWxGroupApply<WxGroupApply> {
	public static final WxGroupApply dao = new WxGroupApply().dao();
}
