/*
 * 使用本软件请从杭州钛特云有限公司获取授权，其它途径获取本软件的行为皆为侵权行为
 * 本源代码由杭州钛特云科技有限公司授权给娄底大新土石方施工有限公司使用
 */
package org.tio.mg.service.model.main;

import org.tio.mg.service.model.main.base.BaseWxGroupMsg;
import org.tio.sitexxx.servicecommon.vo.wx.WxMsgCardVo;
import org.tio.utils.json.Json;

import cn.hutool.core.util.StrUtil;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WxGroupMsg extends BaseWxGroupMsg<WxGroupMsg> {
	public static final WxGroupMsg dao = new WxGroupMsg().dao();
	
	public void setMid(java.lang.Long mid) {
		put("mid", mid);
	}
	
	public java.lang.Long getMid() {
		if(getLong("mid") == null) {
			return getId();
		}
		return getLong("mid");
	}
	
	public void setC(java.lang.String c) {
		put("c", c);
	}
	
	/**
	 * 聊天内容（原始内容）
	 */
	public java.lang.String getC() {
		if(StrUtil.isBlank(getStr("c"))) {
			return getText();
		}
		return getStr("c");
	}
	
	/**
	 * 聊天时间
	 */
	public void setT(java.util.Date t) {
		put("t", t);
	}
	
	/**
	 * 聊天时间
	 */
	public java.util.Date getT() {
		if(get("t") == null) {
			return getTime();
		}
		return get("t");
	}
	/**
	 * 内容类型，1、普通文本消息，2、超链接卡片消息，3、文件，4、音频，5、视频
	 */
	public void setCt(java.lang.Byte ct) {
		put("ct", ct);
	}
	
	/**
	 * 内容类型，1、普通文本消息，2、超链接卡片消息，3、文件，4、音频，5、视频
	 */
	public java.lang.Byte getCt() {
		if(getByte("ct") == null) {
			return getContenttype();
		}
		return getByte("ct");
	}
	
	/**
	 * 昵称
	 */
	public void setNick(java.lang.String nick) {
		put("nick", nick);
	}
	
	/**
	 * 昵称
	 */
	public java.lang.String getNick() {
		return getStr("nick");
	}

	/**
	 * 头像url
	 */
	public void setAvatar(java.lang.String avatar) {
		put("avatar", avatar);
	}
	
	/**
	 * 头像url
	 */
	public java.lang.String getAvatar() {
		return getStr("avatar");
	}
	
	
	/**
	 * 聊天发起人uid
	 */
	public void setF(java.lang.Integer f) {
		put("f", f);
	}
	
	/**
	 * 聊天发起人uid
	 */
	public java.lang.Integer getF() {
		if(getInt("f") == null) {
			return getUid();
		}
		return getInt("f");
	}
	
	/**
	 * 主聊人员的设备类型（DeviceType），1：PC，2：安卓，3：IOS
	 */
	public void setD(java.lang.Byte d) {
		put("d", d);
	}
	
	/**
	 * 主聊人员的设备类型（DeviceType），1：PC，2：安卓，3：IOS
	 */
	public java.lang.Byte getD() {
		if(getByte("d") == null) {
			return getDevice();
		}
		return getByte("d");
	}
	
	/**
	 * 群组id
	 */
	public void setG(java.lang.Long g) {
		put("g", g);
	}
	
	/**
	 * 群组id
	 */
	public java.lang.Long getG() {
		if(getLong("g") == null) {
			return getGroupid();
		}
		return getLong("g");
	}
	
	public Video getVc() {
		String obj = getStr("vc");
		if(StrUtil.isNotBlank(obj)) {
			return Json.toBean(obj, Video.class);
		}
		return null ;
	}

	public String getBc() {
		return getStr("bc");
	}

	public Audio getAc() {
		String obj = getStr("ac");
		if(StrUtil.isNotBlank(obj)) {
			return Json.toBean(obj, Audio.class);
		}
		return null ;
	}


	public File getFc() {
		String obj = getStr("fc");
		if(StrUtil.isNotBlank(obj)) {
			return Json.toBean(obj, File.class);
		}
		return null ;
	}

	public Img getIc() {
		String obj = getStr("ic");
		if(StrUtil.isNotBlank(obj)) {
			return Json.toBean(obj, Img.class);
		}
		return null ;
	}

	public WxMsgCardVo getCardc() {
		String obj = getStr("cardc");
		if(StrUtil.isNotBlank(obj)) {
			return Json.toBean(obj, WxMsgCardVo.class);
		}
		return null ;
	}
}
