package org.tio.mg.service.model.main;

import org.tio.mg.service.model.main.base.BaseWxGroupApplyItems;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WxGroupApplyItems extends BaseWxGroupApplyItems<WxGroupApplyItems> {
	public static final WxGroupApplyItems dao = new WxGroupApplyItems().dao();
}
