package org.tio.mg.service.model.main;

import org.tio.mg.service.model.main.base.BaseYxAdminRecieverAccount;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class YxAdminRecieverAccount extends BaseYxAdminRecieverAccount<YxAdminRecieverAccount> {
	public static final YxAdminRecieverAccount dao = new YxAdminRecieverAccount().dao();
}
