package org.tio.mg.service.model.main;

import org.tio.mg.service.model.main.base.BaseYxTransAccounts;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class YxTransAccounts extends BaseYxTransAccounts<YxTransAccounts> {
	public static final YxTransAccounts dao = new YxTransAccounts().dao();
}
