package org.tio.mg.service.model.main;

import org.tio.mg.service.model.main.base.BaseYxUserRecharge;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class YxUserRecharge extends BaseYxUserRecharge<YxUserRecharge> {
	public static final YxUserRecharge dao = new YxUserRecharge().dao();
}
