package org.tio.mg.service.model.main;

import org.tio.mg.service.model.main.base.BaseYxUserWallet;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class YxUserWallet extends BaseYxUserWallet<YxUserWallet> {
	public static final YxUserWallet dao = new YxUserWallet().dao();
}
