package org.tio.mg.service.model.main.base;

import org.tio.mg.service.jf.TioModel;
import org.tio.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseWxFriendGroup<M extends BaseWxFriendGroup<M>> extends TioModel<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setGroupname(java.lang.String groupname) {
		set("groupname", groupname);
	}
	
	public java.lang.String getGroupname() {
		return getStr("groupname");
	}

	public void setUid(java.lang.Integer uid) {
		set("uid", uid);
	}
	
	public java.lang.Integer getUid() {
		return getInt("uid");
	}

	public void setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
	}
	
	public java.util.Date getCreatetime() {
		return get("createtime");
	}

	public void setFriendidlist(java.lang.String friendidlist) {
		set("friendidlist", friendidlist);
	}
	
	public java.lang.String getFriendidlist() {
		return getStr("friendidlist");
	}

}
