package org.tio.mg.service.model.main.base;

import org.tio.mg.service.jf.TioModel;
import org.tio.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseYxUserRecharge<M extends BaseYxUserRecharge<M>> extends TioModel<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 用户id
	 */
	public void setUid(java.lang.Integer uid) {
		set("uid", uid);
	}
	
	/**
	 * 用户id
	 */
	public java.lang.Integer getUid() {
		return getInt("uid");
	}

	/**
	 * 用户昵称
	 */
	public void setUnick(java.lang.String unick) {
		set("unick", unick);
	}
	
	/**
	 * 用户昵称
	 */
	public java.lang.String getUnick() {
		return getStr("unick");
	}

	/**
	 * 用户钱包ID
	 */
	public void setWalletid(java.lang.Integer walletid) {
		set("walletid", walletid);
	}
	
	/**
	 * 用户钱包ID
	 */
	public java.lang.Integer getWalletid() {
		return getInt("walletid");
	}

	public void setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
	}
	
	public java.util.Date getCreatetime() {
		return get("createtime");
	}

	public void setUpdatetime(java.util.Date updatetime) {
		set("updatetime", updatetime);
	}
	
	public java.util.Date getUpdatetime() {
		return get("updatetime");
	}

	/**
	 * 充值金额
	 */
	public void setAmount(java.lang.Integer amount) {
		set("amount", amount);
	}
	
	/**
	 * 充值金额
	 */
	public java.lang.Integer getAmount() {
		return getInt("amount");
	}

	/**
	 * 支付金额
	 */
	public void setAmountpay(java.lang.Integer amountpay) {
		set("amountpay", amountpay);
	}
	
	/**
	 * 支付金额
	 */
	public java.lang.Integer getAmountpay() {
		return getInt("amountpay");
	}

	/**
	 * 折扣金额，负数表示充值手续费
	 */
	public void setAmountdis(java.lang.Integer amountdis) {
		set("amountdis", amountdis);
	}
	
	/**
	 * 折扣金额，负数表示充值手续费
	 */
	public java.lang.Integer getAmountdis() {
		return getInt("amountdis");
	}

	/**
	 * 支付账号
	 */
	public void setPayacount(java.lang.String payacount) {
		set("payacount", payacount);
	}
	
	/**
	 * 支付账号
	 */
	public java.lang.String getPayacount() {
		return getStr("payacount");
	}

	/**
	 * 11微信SDK 12微信扫码  21支付宝SDK 22支付宝扫码 3银行卡转账 4现金 5活动
	 */
	public void setPaytype(java.lang.Integer paytype) {
		set("paytype", paytype);
	}
	
	/**
	 * 11微信SDK 12微信扫码  21支付宝SDK 22支付宝扫码 3银行卡转账 4现金 5活动
	 */
	public java.lang.Integer getPaytype() {
		return getInt("paytype");
	}

	/**
	 * 支付时备注
	 */
	public void setPayremark(java.lang.String payremark) {
		set("payremark", payremark);
	}
	
	/**
	 * 支付时备注
	 */
	public java.lang.String getPayremark() {
		return getStr("payremark");
	}

	/**
	 * 支付时第三方订单号
	 */
	public void setPay3orderno(java.lang.Integer pay3orderno) {
		set("pay3orderno", pay3orderno);
	}
	
	/**
	 * 支付时第三方订单号
	 */
	public java.lang.Integer getPay3orderno() {
		return getInt("pay3orderno");
	}

	/**
	 * 流水号
	 */
	public void setSerial(java.lang.String serial) {
		set("serial", serial);
	}
	
	/**
	 * 流水号
	 */
	public java.lang.String getSerial() {
		return getStr("serial");
	}

	/**
	 * 充值状态：1待审核 2审核中 3已通过 4拒绝5充值完成
	 */
	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}
	
	/**
	 * 充值状态：1待审核 2审核中 3已通过 4拒绝5充值完成
	 */
	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	/**
	 * 审核人ID
	 */
	public void setReviewuid(java.lang.Integer reviewuid) {
		set("reviewuid", reviewuid);
	}
	
	/**
	 * 审核人ID
	 */
	public java.lang.Integer getReviewuid() {
		return getInt("reviewuid");
	}

	/**
	 * 审核时间完成时间
	 */
	public void setReviewtime(java.util.Date reviewtime) {
		set("reviewtime", reviewtime);
	}
	
	/**
	 * 审核时间完成时间
	 */
	public java.util.Date getReviewtime() {
		return get("reviewtime");
	}

	/**
	 * 审核意见
	 */
	public void setReviewremark(java.lang.String reviewremark) {
		set("reviewremark", reviewremark);
	}
	
	/**
	 * 审核意见
	 */
	public java.lang.String getReviewremark() {
		return getStr("reviewremark");
	}

	public void setExt1(java.lang.String ext1) {
		set("ext1", ext1);
	}
	
	public java.lang.String getExt1() {
		return getStr("ext1");
	}

	public void setExt2(java.lang.String ext2) {
		set("ext2", ext2);
	}
	
	public java.lang.String getExt2() {
		return getStr("ext2");
	}

	public void setExt3(java.lang.String ext3) {
		set("ext3", ext3);
	}
	
	public java.lang.String getExt3() {
		return getStr("ext3");
	}

}
