package org.tio.mg.service.model.main.base;

import org.tio.mg.service.jf.TioModel;
import org.tio.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUserInviteAttr<M extends BaseUserInviteAttr<M>> extends TioModel<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	/**
	 * 所属UID
	 */
	public void setUid(java.lang.Integer uid) {
		set("uid", uid);
	}
	
	/**
	 * 所属UID
	 */
	public java.lang.Integer getUid() {
		return getInt("uid");
	}

	public void setInvitecode(java.lang.String invitecode) {
		set("invitecode", invitecode);
	}
	
	public java.lang.String getInvitecode() {
		return getStr("invitecode");
	}

	/**
	 * 状态 1：绑定，2：解绑
	 */
	public void setStatus(java.lang.Byte status) {
		set("status", status);
	}
	
	/**
	 * 状态 1：绑定，2：解绑
	 */
	public java.lang.Byte getStatus() {
		return getByte("status");
	}

	/**
	 * 默认要加的好友ID
	 */
	public void setFuid(java.lang.String fuid) {
		set("fuid", fuid);
	}
	
	/**
	 * 默认要加的好友ID
	 */
	public java.lang.String getFuid() {
		return getStr("fuid");
	}

	/**
	 * 默认要加的群ID
	 */
	public void setGid(java.lang.Integer gid) {
		set("gid", gid);
	}
	
	/**
	 * 默认要加的群ID
	 */
	public java.lang.Integer getGid() {
		return getInt("gid");
	}

	/**
	 * 默认要发的信息
	 */
	public void setMessage(java.lang.String message) {
		set("message", message);
	}
	
	/**
	 * 默认要发的信息
	 */
	public java.lang.String getMessage() {
		return getStr("message");
	}

}
