package org.tio.mg.service.model.main.base;

import org.tio.mg.service.jf.TioModel;
import org.tio.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseRechargeItem<M extends BaseRechargeItem<M>> extends TioModel<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 用户id
	 */
	public void setUserid(java.lang.Integer userid) {
		set("userid", userid);
	}
	
	/**
	 * 用户id
	 */
	public java.lang.Integer getUserid() {
		return getInt("userid");
	}

	/**
	 * 本系统的交易号
	 */
	public void setTradeno(java.lang.String tradeno) {
		set("tradeno", tradeno);
	}
	
	/**
	 * 本系统的交易号
	 */
	public java.lang.String getTradeno() {
		return getStr("tradeno");
	}

	/**
	 * 在本系统中的交易时间
	 */
	public void setTradetime(java.util.Date tradetime) {
		set("tradetime", tradetime);
	}
	
	/**
	 * 在本系统中的交易时间
	 */
	public java.util.Date getTradetime() {
		return get("tradetime");
	}

	/**
	 * 订单状态1-未付款 2-已付款 3-取消订单 4-已完成 9-攻击充值 99-异常
	 */
	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}
	
	/**
	 * 订单状态1-未付款 2-已付款 3-取消订单 4-已完成 9-攻击充值 99-异常
	 */
	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	/**
	 * 充值现金数，单位(人民币：元)
	 */
	public void setAmount(java.lang.Double amount) {
		set("amount", amount);
	}
	
	/**
	 * 充值现金数，单位(人民币：元)
	 */
	public java.lang.Double getAmount() {
		return getDouble("amount");
	}

	/**
	 * 支付方式:
1:支付宝
2:微信

11:手机版支付宝
22:手机版微信
	 */
	public void setPaytype(java.lang.Integer paytype) {
		set("paytype", paytype);
	}
	
	/**
	 * 支付方式:
1:支付宝
2:微信

11:手机版支付宝
22:手机版微信
	 */
	public java.lang.Integer getPaytype() {
		return getInt("paytype");
	}

	/**
	 * 商品名
	 */
	public void setGoods(java.lang.String goods) {
		set("goods", goods);
	}
	
	/**
	 * 商品名
	 */
	public java.lang.String getGoods() {
		return getStr("goods");
	}

	/**
	 * 商品数量
	 */
	public void setGoodscount(java.lang.Integer goodscount) {
		set("goodscount", goodscount);
	}
	
	/**
	 * 商品数量
	 */
	public java.lang.Integer getGoodscount() {
		return getInt("goodscount");
	}

	/**
	 * 客户端类型1-pc 2-android 3-ios
	 */
	public void setClienttype(java.lang.Integer clienttype) {
		set("clienttype", clienttype);
	}
	
	/**
	 * 客户端类型1-pc 2-android 3-ios
	 */
	public java.lang.Integer getClienttype() {
		return getInt("clienttype");
	}

	/**
	 * 客户端型号。如果是手机充值，则是手机型号，譬如华为P9，如果是PC，则是浏览器信息
	 */
	public void setClientinfo(java.lang.String clientinfo) {
		set("clientinfo", clientinfo);
	}
	
	/**
	 * 客户端型号。如果是手机充值，则是手机型号，譬如华为P9，如果是PC，则是浏览器信息
	 */
	public java.lang.String getClientinfo() {
		return getStr("clientinfo");
	}

	/**
	 * 对应user_agent的id字段
	 */
	public void setUseragentid(java.lang.Integer useragentid) {
		set("useragentid", useragentid);
	}
	
	/**
	 * 对应user_agent的id字段
	 */
	public java.lang.Integer getUseragentid() {
		return getInt("useragentid");
	}

	/**
	 * 客户端充值时的ip地址
	 */
	public void setRemoteip(java.lang.String remoteip) {
		set("remoteip", remoteip);
	}
	
	/**
	 * 客户端充值时的ip地址
	 */
	public java.lang.String getRemoteip() {
		return getStr("remoteip");
	}

	/**
	 * 回调时的远端ip
	 */
	public void setRemoteipnotify(java.lang.String remoteipnotify) {
		set("remoteipnotify", remoteipnotify);
	}
	
	/**
	 * 回调时的远端ip
	 */
	public java.lang.String getRemoteipnotify() {
		return getStr("remoteipnotify");
	}

	/**
	 * 入口页
	 */
	public void setReferer(java.lang.String referer) {
		set("referer", referer);
	}
	
	/**
	 * 入口页
	 */
	public java.lang.String getReferer() {
		return getStr("referer");
	}

	/**
	 * 回调页
	 */
	public void setCallback(java.lang.String callback) {
		set("callback", callback);
	}
	
	/**
	 * 回调页
	 */
	public java.lang.String getCallback() {
		return getStr("callback");
	}

	/**
	 * 第三方支付平台的交易号
	 */
	public void setThirdtradeno(java.lang.String thirdtradeno) {
		set("thirdtradeno", thirdtradeno);
	}
	
	/**
	 * 第三方支付平台的交易号
	 */
	public java.lang.String getThirdtradeno() {
		return getStr("thirdtradeno");
	}

	/**
	 * 第三方支付平台的支付状态
	 */
	public void setThirdstatus(java.lang.String thirdstatus) {
		set("thirdstatus", thirdstatus);
	}
	
	/**
	 * 第三方支付平台的支付状态
	 */
	public java.lang.String getThirdstatus() {
		return getStr("thirdstatus");
	}

	/**
	 * 第三方交易通知时间
	 */
	public void setThirdtradetime(java.util.Date thirdtradetime) {
		set("thirdtradetime", thirdtradetime);
	}
	
	/**
	 * 第三方交易通知时间
	 */
	public java.util.Date getThirdtradetime() {
		return get("thirdtradetime");
	}

	/**
	 * 买家在第三方支付平台的帐号，譬如支付宝就是支付宝的登录帐号
	 */
	public void setThirdaccount(java.lang.String thirdaccount) {
		set("thirdaccount", thirdaccount);
	}
	
	/**
	 * 买家在第三方支付平台的帐号，譬如支付宝就是支付宝的登录帐号
	 */
	public java.lang.String getThirdaccount() {
		return getStr("thirdaccount");
	}

	/**
	 * 支付平台返回的金额(单位元，如果支付平台的单位不是元，需要换算成元）
	 */
	public void setThirdamount(java.lang.Double thirdamount) {
		set("thirdamount", thirdamount);
	}
	
	/**
	 * 支付平台返回的金额(单位元，如果支付平台的单位不是元，需要换算成元）
	 */
	public java.lang.Double getThirdamount() {
		return getDouble("thirdamount");
	}

	/**
	 * 支付平台的通知id
	 */
	public void setThirdnotifyid(java.lang.String thirdnotifyid) {
		set("thirdnotifyid", thirdnotifyid);
	}
	
	/**
	 * 支付平台的通知id
	 */
	public java.lang.String getThirdnotifyid() {
		return getStr("thirdnotifyid");
	}

	/**
	 * 用来存其它信息
	 */
	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}
	
	/**
	 * 用来存其它信息
	 */
	public java.lang.String getRemark() {
		return getStr("remark");
	}

	/**
	 * 如果是苹果支付，则有此值，表示receipt
	 */
	public void setReceipt(java.lang.String receipt) {
		set("receipt", receipt);
	}
	
	/**
	 * 如果是苹果支付，则有此值，表示receipt
	 */
	public java.lang.String getReceipt() {
		return getStr("receipt");
	}

	/**
	 * 该条记录更新时间
	 */
	public void setUpdatetime(java.util.Date updatetime) {
		set("updatetime", updatetime);
	}
	
	/**
	 * 该条记录更新时间
	 */
	public java.util.Date getUpdatetime() {
		return get("updatetime");
	}

	/**
	 * 创建时间
	 */
	public void setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreatetime() {
		return get("createtime");
	}

	/**
	 * 业务id
	 */
	public void setBizid(java.lang.String bizid) {
		set("bizid", bizid);
	}
	
	/**
	 * 业务id
	 */
	public java.lang.String getBizid() {
		return getStr("bizid");
	}

	/**
	 * 该笔充值用于什么业务类型
	 */
	public void setBiztype(java.lang.Byte biztype) {
		set("biztype", biztype);
	}
	
	/**
	 * 该笔充值用于什么业务类型
	 */
	public java.lang.Byte getBiztype() {
		return getByte("biztype");
	}

}
