package org.tio.mg.service.model.main.base;

import org.tio.mg.service.jf.TioModel;
import org.tio.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseYxUserWithdrawAccount<M extends BaseYxUserWithdrawAccount<M>> extends TioModel<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 用户id
	 */
	public void setUid(java.lang.Integer uid) {
		set("uid", uid);
	}
	
	/**
	 * 用户id
	 */
	public java.lang.Integer getUid() {
		return getInt("uid");
	}

	public void setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
	}
	
	public java.util.Date getCreatetime() {
		return get("createtime");
	}

	public void setUpdatetime(java.util.Date updatetime) {
		set("updatetime", updatetime);
	}
	
	public java.util.Date getUpdatetime() {
		return get("updatetime");
	}

	/**
	 * 账户类型：1微信2支付宝3银行卡
	 */
	public void setAccounttype(java.lang.Integer accounttype) {
		set("accounttype", accounttype);
	}
	
	/**
	 * 账户类型：1微信2支付宝3银行卡
	 */
	public java.lang.Integer getAccounttype() {
		return getInt("accounttype");
	}

	/**
	 * 账户名
	 */
	public void setAccountname(java.lang.String accountname) {
		set("accountname", accountname);
	}
	
	/**
	 * 账户名
	 */
	public java.lang.String getAccountname() {
		return getStr("accountname");
	}

	/**
	 * 账户账号
	 */
	public void setAccountno(java.lang.String accountno) {
		set("accountno", accountno);
	}
	
	/**
	 * 账户账号
	 */
	public java.lang.String getAccountno() {
		return getStr("accountno");
	}

	public void setBankname(java.lang.String bankname) {
		set("bankname", bankname);
	}
	
	public java.lang.String getBankname() {
		return getStr("bankname");
	}

	/**
	 * 银行账户运行名称
	 */
	public void setBrandname(java.lang.String brandname) {
		set("brandname", brandname);
	}
	
	/**
	 * 银行账户运行名称
	 */
	public java.lang.String getBrandname() {
		return getStr("brandname");
	}

	/**
	 * 备注
	 */
	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}
	
	/**
	 * 备注
	 */
	public java.lang.String getRemark() {
		return getStr("remark");
	}

	/**
	 * 删除标记0正常1删除
	 */
	public void setDelflag(java.lang.Integer delflag) {
		set("delflag", delflag);
	}
	
	/**
	 * 删除标记0正常1删除
	 */
	public java.lang.Integer getDelflag() {
		return getInt("delflag");
	}

	public void setExt1(java.lang.String ext1) {
		set("ext1", ext1);
	}
	
	public java.lang.String getExt1() {
		return getStr("ext1");
	}

	public void setExt2(java.lang.String ext2) {
		set("ext2", ext2);
	}
	
	public java.lang.String getExt2() {
		return getStr("ext2");
	}

	public void setExt3(java.lang.String ext3) {
		set("ext3", ext3);
	}
	
	public java.lang.String getExt3() {
		return getStr("ext3");
	}

}
