package org.tio.mg.service.model.main.base;

import org.tio.mg.service.jf.TioModel;
import org.tio.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUserInvite<M extends BaseUserInvite<M>> extends TioModel<M> implements IBean {

	/**
	 * 用户邀请关联id
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	/**
	 * 用户邀请关联id
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 邀请的用户uid
	 */
	public void setInviteUid(java.lang.Integer inviteUid) {
		set("invite_uid", inviteUid);
	}
	
	/**
	 * 邀请的用户uid
	 */
	public java.lang.Integer getInviteUid() {
		return getInt("invite_uid");
	}

	/**
	 * 邀请码
	 */
	public void setInviteCode(java.lang.String inviteCode) {
		set("invite_code", inviteCode);
	}
	
	/**
	 * 邀请码
	 */
	public java.lang.String getInviteCode() {
		return getStr("invite_code");
	}

	/**
	 * 注册用户uid
	 */
	public void setRegisterUid(java.lang.Integer registerUid) {
		set("register_uid", registerUid);
	}
	
	/**
	 * 注册用户uid
	 */
	public java.lang.Integer getRegisterUid() {
		return getInt("register_uid");
	}

	/**
	 * 邀请方式0:app分享
	 */
	public void setInviteType(java.lang.Integer inviteType) {
		set("invite_type", inviteType);
	}
	
	/**
	 * 邀请方式0:app分享
	 */
	public java.lang.Integer getInviteType() {
		return getInt("invite_type");
	}

	/**
	 * 邀请标语
	 */
	public void setInviteText(java.lang.String inviteText) {
		set("invite_text", inviteText);
	}
	
	/**
	 * 邀请标语
	 */
	public java.lang.String getInviteText() {
		return getStr("invite_text");
	}

	/**
	 * 邀请渠道
	 */
	public void setInviteChannel(java.lang.String inviteChannel) {
		set("invite_channel", inviteChannel);
	}
	
	/**
	 * 邀请渠道
	 */
	public java.lang.String getInviteChannel() {
		return getStr("invite_channel");
	}

	/**
	 * 邀请说明
	 */
	public void setInviteExplain(java.lang.String inviteExplain) {
		set("invite_explain", inviteExplain);
	}
	
	/**
	 * 邀请说明
	 */
	public java.lang.String getInviteExplain() {
		return getStr("invite_explain");
	}

	/**
	 * 创建时间
	 */
	public void setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreatetime() {
		return get("createtime");
	}

}
