package org.tio.mg.service.model.main.base;

import org.tio.mg.service.jf.TioModel;
import org.tio.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUserVipLevel<M extends BaseUserVipLevel<M>> extends TioModel<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}
	
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public void setVipLevel(java.lang.Integer vipLevel) {
		set("vip_level", vipLevel);
	}
	
	public java.lang.Integer getVipLevel() {
		return getInt("vip_level");
	}

	public void setMaxCreateGroup(java.lang.Integer maxCreateGroup) {
		set("max_create_group", maxCreateGroup);
	}
	
	public java.lang.Integer getMaxCreateGroup() {
		return getInt("max_create_group");
	}

	public void setMaxAddFriend(java.lang.Integer maxAddFriend) {
		set("max_add_friend", maxAddFriend);
	}
	
	public java.lang.Integer getMaxAddFriend() {
		return getInt("max_add_friend");
	}

}
