package org.tio.mg.service.model.main.base;

import org.tio.mg.service.jf.TioModel;
import org.tio.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseYxUserSendRedPacket<M extends BaseYxUserSendRedPacket<M>> extends TioModel<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 发送人id
	 */
	public void setSenduid(java.lang.Integer senduid) {
		set("senduid", senduid);
	}
	
	/**
	 * 发送人id
	 */
	public java.lang.Integer getSenduid() {
		return getInt("senduid");
	}

	/**
	 * 发送人昵称
	 */
	public void setSendnick(java.lang.String sendnick) {
		set("sendnick", sendnick);
	}
	
	/**
	 * 发送人昵称
	 */
	public java.lang.String getSendnick() {
		return getStr("sendnick");
	}

	/**
	 * 记录创建时间
	 */
	public void setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
	}
	
	/**
	 * 记录创建时间
	 */
	public java.util.Date getCreatetime() {
		return get("createtime");
	}

	/**
	 * 该记录更新时间
	 */
	public void setUpdatetime(java.util.Date updatetime) {
		set("updatetime", updatetime);
	}
	
	/**
	 * 该记录更新时间
	 */
	public java.util.Date getUpdatetime() {
		return get("updatetime");
	}

	/**
	 * 红包金额
	 */
	public void setMoney(java.lang.Integer money) {
		set("money", money);
	}
	
	/**
	 * 红包金额
	 */
	public java.lang.Integer getMoney() {
		return getInt("money");
	}

	/**
	 * 类型 1：单人红包 21：群普通红包 22：群拼手气红包
	 */
	public void setMode(java.lang.Integer mode) {
		set("mode", mode);
	}
	
	/**
	 * 类型 1：单人红包 21：群普通红包 22：群拼手气红包
	 */
	public java.lang.Integer getMode() {
		return getInt("mode");
	}

	/**
	 * 红包个数
	 */
	public void setNum(java.lang.Integer num) {
		set("num", num);
	}
	
	/**
	 * 红包个数
	 */
	public java.lang.Integer getNum() {
		return getInt("num");
	}

	/**
	 * 剩余个数
	 */
	public void setRemainnum(java.lang.Integer remainnum) {
		set("remainnum", remainnum);
	}
	
	/**
	 * 剩余个数
	 */
	public java.lang.Integer getRemainnum() {
		return getInt("remainnum");
	}

	/**
	 * 剩余金额
	 */
	public void setRemainmoney(java.lang.Integer remainmoney) {
		set("remainmoney", remainmoney);
	}
	
	/**
	 * 剩余金额
	 */
	public java.lang.Integer getRemainmoney() {
		return getInt("remainmoney");
	}

	/**
	 * 接收人ID，群为群ID，个人为用户ID
	 */
	public void setToid(java.lang.Long toid) {
		set("toid", toid);
	}
	
	/**
	 * 接收人ID，群为群ID，个人为用户ID
	 */
	public java.lang.Long getToid() {
		return getLong("toid");
	}

	/**
	 * 会话ID
	 */
	public void setChatlinkid(java.lang.Long chatlinkid) {
		set("chatlinkid", chatlinkid);
	}
	
	/**
	 * 会话ID
	 */
	public java.lang.Long getChatlinkid() {
		return getLong("chatlinkid");
	}

	/**
	 * 红包状态：1初始化未支付2已支付可以抢3已抢完4已过期
	 */
	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}
	
	/**
	 * 红包状态：1初始化未支付2已支付可以抢3已抢完4已过期
	 */
	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	/**
	 * 备注
	 */
	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}
	
	/**
	 * 备注
	 */
	public java.lang.String getRemark() {
		return getStr("remark");
	}

	public void setExt1(java.lang.String ext1) {
		set("ext1", ext1);
	}
	
	public java.lang.String getExt1() {
		return getStr("ext1");
	}

	public void setExt2(java.lang.String ext2) {
		set("ext2", ext2);
	}
	
	public java.lang.String getExt2() {
		return getStr("ext2");
	}

	public void setExt3(java.lang.String ext3) {
		set("ext3", ext3);
	}
	
	public java.lang.String getExt3() {
		return getStr("ext3");
	}

	/**
	 * 发送人IP
	 */
	public void setSendip(java.lang.String sendip) {
		set("sendip", sendip);
	}
	
	/**
	 * 发送人IP
	 */
	public java.lang.String getSendip() {
		return getStr("sendip");
	}

	/**
	 * 设备类型
	 */
	public void setDevicetype(java.lang.Byte devicetype) {
		set("devicetype", devicetype);
	}
	
	/**
	 * 设备类型
	 */
	public java.lang.Byte getDevicetype() {
		return getByte("devicetype");
	}

	public void setAppver(java.lang.String appver) {
		set("appver", appver);
	}
	
	public java.lang.String getAppver() {
		return getStr("appver");
	}

}
