package org.tio.mg.service.model.main.base;

import org.tio.mg.service.jf.TioModel;
import org.tio.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUserCoin<M extends BaseUserCoin<M>> extends TioModel<M> implements IBean {

	/**
	 * ID
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	/**
	 * ID
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 用户id
	 */
	public void setUid(java.lang.Integer uid) {
		set("uid", uid);
	}
	
	/**
	 * 用户id
	 */
	public java.lang.Integer getUid() {
		return getInt("uid");
	}

	/**
	 * 牛币余额
	 */
	public void setCoin(java.lang.Double coin) {
		set("coin", coin);
	}
	
	/**
	 * 牛币余额
	 */
	public java.lang.Double getCoin() {
		return getDouble("coin");
	}

	/**
	 * 已消费牛币
	 */
	public void setCostcoin(java.lang.Double costcoin) {
		set("costcoin", costcoin);
	}
	
	/**
	 * 已消费牛币
	 */
	public java.lang.Double getCostcoin() {
		return getDouble("costcoin");
	}

	/**
	 * 总牛币
	 */
	public void setTotalcoin(java.lang.Double totalcoin) {
		set("totalcoin", totalcoin);
	}
	
	/**
	 * 总牛币
	 */
	public java.lang.Double getTotalcoin() {
		return getDouble("totalcoin");
	}

	/**
	 * 牛丸
	 */
	public void setFreecoin(java.lang.Double freecoin) {
		set("freecoin", freecoin);
	}
	
	/**
	 * 牛丸
	 */
	public java.lang.Double getFreecoin() {
		return getDouble("freecoin");
	}

	/**
	 * 已消费牛丸
	 */
	public void setCostfreecoin(java.lang.Double costfreecoin) {
		set("costfreecoin", costfreecoin);
	}
	
	/**
	 * 已消费牛丸
	 */
	public java.lang.Double getCostfreecoin() {
		return getDouble("costfreecoin");
	}

	/**
	 * 获得的总牛丸
	 */
	public void setTotalfreecoin(java.lang.Double totalfreecoin) {
		set("totalfreecoin", totalfreecoin);
	}
	
	/**
	 * 获得的总牛丸
	 */
	public java.lang.Double getTotalfreecoin() {
		return getDouble("totalfreecoin");
	}

	/**
	 * 人民币
	 */
	public void setCny(java.lang.Double cny) {
		set("cny", cny);
	}
	
	/**
	 * 人民币
	 */
	public java.lang.Double getCny() {
		return getDouble("cny");
	}

	/**
	 * 提现人民币
	 */
	public void setWithdrawcny(java.lang.Double withdrawcny) {
		set("withdrawcny", withdrawcny);
	}
	
	/**
	 * 提现人民币
	 */
	public java.lang.Double getWithdrawcny() {
		return getDouble("withdrawcny");
	}

	/**
	 * 总人民币收入
	 */
	public void setTotalcny(java.lang.Double totalcny) {
		set("totalcny", totalcny);
	}
	
	/**
	 * 总人民币收入
	 */
	public java.lang.Double getTotalcny() {
		return getDouble("totalcny");
	}

	/**
	 * 冻结人民币
	 */
	public void setFreezecny(java.lang.Double freezecny) {
		set("freezecny", freezecny);
	}
	
	/**
	 * 冻结人民币
	 */
	public java.lang.Double getFreezecny() {
		return getDouble("freezecny");
	}

	/**
	 * 通过非法手段充值得到的牛币
	 */
	public void setAttackcoin(java.lang.Double attackcoin) {
		set("attackcoin", attackcoin);
	}
	
	/**
	 * 通过非法手段充值得到的牛币
	 */
	public java.lang.Double getAttackcoin() {
		return getDouble("attackcoin");
	}

	/**
	 * 总贡献值
	 */
	public void setTotaldevote(java.lang.Double totaldevote) {
		set("totaldevote", totaldevote);
	}
	
	/**
	 * 总贡献值
	 */
	public java.lang.Double getTotaldevote() {
		return getDouble("totaldevote");
	}

	/**
	 * 状态：1：正常；3：删除
	 */
	public void setStatus(java.lang.Byte status) {
		set("status", status);
	}
	
	/**
	 * 状态：1：正常；3：删除
	 */
	public java.lang.Byte getStatus() {
		return getByte("status");
	}

	/**
	 * 注销标识
	 */
	public void setDelsign(java.lang.String delsign) {
		set("delsign", delsign);
	}
	
	/**
	 * 注销标识
	 */
	public java.lang.String getDelsign() {
		return getStr("delsign");
	}

	/**
	 * 创建时间
	 */
	public void setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreatetime() {
		return get("createtime");
	}

	/**
	 * 修改时间
	 */
	public void setUpdatetime(java.util.Date updatetime) {
		set("updatetime", updatetime);
	}
	
	/**
	 * 修改时间
	 */
	public java.util.Date getUpdatetime() {
		return get("updatetime");
	}

}
